const publicName = value => {
  if (typeof value !== 'string') return '';
  const text = value.trim();
  if (!text || ['null', 'undefined', 'none', 'unknown', 'user', 'creator', 'post'].includes(text.toLowerCase())) return '';
  // Never expose an email address, even when a legacy post stores it as a name.
  if (text.includes('@') && !/^@[\w.-]+$/.test(text)) return '';
  return text.slice(0, 80);
};

export function isSystemPostAuthor(post) {
  return Boolean(post?.isLearningGuide || post?.isAutoGenerated || post?.isSystemGenerated
    || [post?.authorId, post?.authorID, post?.author_id, post?.creatorId].some(value => String(value || '').toLowerCase() === 'smarty-ai')
    || [post?.author, post?.creatorName, post?.authorName].some(value => typeof value === 'string' && ['smarty ai', 'smarty-ai'].includes(value.trim().toLowerCase())));
}

export function getPostAuthorId(post) {
  if (isSystemPostAuthor(post)) return '';
  const id = [post?.creatorId, post?.creatorID, post?.creator_id, post?.authorId, post?.authorID, post?.author_id,
    post?.userId, post?.userID, post?.user_id, post?.author?.id, post?.author?.userId, post?.author?.sub,
    post?.creator?.id, post?.creator?.userId, post?.user?.id, post?.user?.userId, post?.user?.sub]
    .find(value => (typeof value === 'string' || typeof value === 'number') && String(value).trim() && !String(value).includes('@'));
  return id == null ? '' : String(id).trim();
}

export function getPostAuthorUsername(post, response = null) {
  if (post?.isLearningGuide) return 'Smarty learning guide';
  if (isSystemPostAuthor(post)) return 'Smarty AI';
  const profile = response?.profile || response?.user || response || {};
  const nested = [post?.author, post?.creator, post?.user].filter(value => value && typeof value === 'object');
  const candidates = [profile.username, profile.userName, profile.handle,
    post?.creatorUsername, post?.authorUsername, post?.username, post?.userName,
    ...nested.flatMap(value => [value.username, value.userName, value.handle]),
    profile.displayName, profile.name, post?.displayName, post?.creatorName, post?.authorName,
    post?.author, ...nested.flatMap(value => [value.displayName, value.name])];
  return candidates.map(publicName).find(Boolean) || 'Smarty member';
}
