import { memo, useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Link, useLocation, useNavigate, useParams } from 'react-router-dom';
import {
  ArrowLeft,
  ArrowRight,
  Bookmark,
  MessageCircle,
  Bot,
  Loader2,
  Sparkles,
  Globe2,
  Brain,
  Microscope,
  Cpu,
  Code2,
  TrendingUp,
  HeartPulse,
  GraduationCap,
  Scale,
  Compass,
  Rocket,
  RefreshCw,
  MoonStar,
  Lightbulb,
  MoreHorizontal,
  Flag,
  UserX,
  X,
} from 'lucide-react';
import SmartyBrand from '../components/SmartyBrand';
import { postApi, creatorApi, chatApi } from '../api/client';
import FeedSkeleton from '../components/FeedSkeleton';
import useFeed from '../hooks/useFeed';
import { useAuth } from '../contexts/AuthContext';
import './FeedPage.css';

const normalizeTopic = (value) =>
  String(value || '')
    .normalize('NFKD')
    .toLowerCase()
    .trim()
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');

const TOPIC_ALIASES = new Map([
  ['ai', 'artificial-intelligence'],
  ['artificial-intelligence', 'artificial-intelligence'],
  ['tech', 'technology'],
  ['technology', 'technology'],
  ['programming', 'coding'],
  ['software-development', 'coding'],
  ['coding', 'coding'],
  ['mental-health', 'psychology'],
]);

const getCanonicalTopic = (value) => {
  const normalized = normalizeTopic(value);

  return TOPIC_ALIASES.get(normalized) || normalized;
};

const areTopicsEquivalent = (left, right) => {
  const normalizedLeft = getCanonicalTopic(left);
  const normalizedRight = getCanonicalTopic(right);

  return Boolean(
    normalizedLeft &&
      normalizedRight &&
      normalizedLeft === normalizedRight
  );
};

const getTopicValue = (value) => {
  if (value && typeof value === 'object') {
    return String(
      value.name ||
        value.label ||
        value.title ||
        value.topic ||
        value.topicName ||
        value.slug ||
        value.id ||
        ''
    ).trim();
  }

  return String(value || '').trim();
};

const getPostTopics = (post) => {
  const rawValues = [
    post?.topic,
    post?.topics,
    post?.category,
    post?.categories,
    post?.roomName,
    post?.subject,
    post?.tags,
  ];

  return rawValues
    .flatMap((value) => {
      if (Array.isArray(value)) {
        return value;
      }

      if (
        typeof value === 'string' &&
        value.includes(',')
      ) {
        return value.split(',');
      }

      return [value];
    })
    .map(getTopicValue)
    .filter(Boolean);
};

const getPostId = (post) => post?.reelId || post?.id || '';

const getPostTime = (post) => Number(post?.createdAtMs || post?.updatedAtMs || post?.createdAt || post?.updatedAt || post?.timestamp || 0);

const normalizeCreatorProfile = (value) => value?.profile || value?.user || value || null;


const INITIAL_RENDER_LIMIT = 10;
const RENDER_BATCH_SIZE = 8;

const INITIAL_TOPIC_LIMIT = 12;
const TOPIC_BATCH_SIZE = 4;
const FAST_IMAGE_LIMIT = 4;
const IMAGE_PRELOAD_MARGIN = '900px';
const FEED_SCROLL_STORAGE_KEY = 'smarty.feed.scrollY';
const FEED_RENDER_LIMIT_STORAGE_KEY = 'smarty.feed.renderLimit';
const FEED_POST_ID_STORAGE_KEY = 'smarty.feed.postId';
const MODERATION_REASONS = [
  'Harassment or bullying',
  'Hate speech',
  'Sexual or explicit content',
  'Violence or threats',
  'Spam or scam',
  'Other objectionable content',
];

const getPostCreatorId = (post) => {
  const creatorId =
    post?.creatorId ||
    post?.creatorID ||
    post?.creator_id ||
    post?.authorId ||
    post?.authorID ||
    post?.author_id ||
    post?.userId ||
    post?.userID ||
    post?.user_id ||
    post?.author?.id ||
    post?.author?.userId ||
    post?.creator?.id ||
    post?.creator?.userId ||
    post?.user?.id ||
    post?.user?.userId ||
    '';

  return String(creatorId || '').trim();
};

const isSystemGeneratedPost = (post) => {
  const authorId = String(
    post?.authorId ||
    post?.authorID ||
    post?.author_id ||
    ''
  ).trim().toLowerCase();

  const authorName = String(
    post?.author ||
    post?.creatorName ||
    post?.authorName ||
    ''
  ).trim().toLowerCase();

  return Boolean(
    post?.isAutoGenerated ||
    post?.isSystemGenerated ||
    authorId === 'smarty-ai' ||
    authorName === 'smarty ai' ||
    authorName === 'smarty-ai'
  );
};




const getDisplayUsername = (post, creatorProfile = null) => {
  const profile = creatorProfile?.profile || creatorProfile?.user || creatorProfile || {};

  const databasePostNames = [
    post.creatorName,
    post.authorName,
    post.author,
    post.creatorEmail,
    post.authorEmail,
    post.email,
    post.creatorUsername,
    post.authorUsername,
    post.username,
    post.userName,
    post.displayName,
  ];

  const profileNames = [
    profile.username,
    profile.userName,
    profile.displayName,
    profile.name,
    profile.email,
  ];

  const nestedPostNames = [
    post.author?.username,
    post.author?.userName,
    post.author?.displayName,
    post.author?.name,
    post.author?.email,
    post.creator?.username,
    post.creator?.userName,
    post.creator?.displayName,
    post.creator?.name,
    post.creator?.email,
    post.user?.username,
    post.user?.userName,
    post.user?.displayName,
    post.user?.name,
    post.user?.email,
  ];

  const blockedValues = new Set([
    '',
    'null',
    'undefined',
    'none',
    'post',
    'creator',
    'unknown',
  ]);

  const formatName = (value) => {
    const text = String(value || '').trim();
    if (!text || blockedValues.has(text.toLowerCase())) return '';

    if (text.includes('@')) {
      return text.split('@')[0] || 'user';
    }

    return text;
  };

  const pickName = (values) => {
    for (const value of values) {
      const text = formatName(value);
      if (text) return text;
    }
    return '';
  };

  return pickName(databasePostNames) || pickName(profileNames) || pickName(nestedPostNames) || 'user';
};

const getCachedExplanation = (post) => {
  const value =
    post?.aiExplanation ||
    post?.simpleExplanation ||
    post?.explanation ||
    post?.explainText ||
    post?.simplifiedText ||
    '';

  const text = String(value || '').trim();
  return text && text.toLowerCase() !== 'null' && text.toLowerCase() !== 'undefined'
    ? text
    : '';
};

const getTopicVisualMeta = (topicName, index = 0) => {
  const normalized = normalizeTopic(topicName);

  const topicPalettes = {
    all: {
      icon: Globe2,
      label: 'Everything',
      description: 'Explore the full Smarty feed',
    },

    psychology: {
      icon: Brain,
      label: 'Mind Lab',
      description: 'Human behaviour, cognition, and mental health',
    },

    science: {
      icon: Microscope,
      label: 'Discovery Mode',
      description: 'Experiments, facts, and curiosity',
    },

    technology: {
      icon: Cpu,
      label: 'Future Stack',
      description: 'AI, cloud, apps, and modern tools',
    },

    coding: {
      icon: Code2,
      label: 'Build Mode',
      description: 'Programming, projects, and engineering',
    },

    business: {
      icon: TrendingUp,
      label: 'Growth Room',
      description: 'Startups, strategy, and money',
    },

    health: {
      icon: HeartPulse,
      label: 'Wellness Hub',
      description: 'Body, lifestyle, and care',
    },

    education: {
      icon: GraduationCap,
      label: 'Study Zone',
      description: 'Concepts, revision, and learning',
    },

    law: {
      icon: Scale,
      label: 'Case Mode',
      description: 'Rules, rights, and legal reasoning',
    },
  };

  const fallbackTopics = [
    {
      icon: Sparkles,
      label: 'Smart Pick',
      description: 'Fresh ideas selected for you',
    },
    {
      icon: Rocket,
      label: 'Deep Dive',
      description: 'Explore this learning lane',
    },
    {
      icon: MoonStar,
      label: 'Focus Flow',
      description: 'Calm, focused topic discovery',
    },
    {
      icon: Lightbulb,
      label: 'Idea Spark',
      description: 'Quick knowledge worth saving',
    },
  ];

  return (
    topicPalettes[normalized] ||
    fallbackTopics[index % fallbackTopics.length]
  );
};

const uniqueTopicList = (values = []) => {
  const topicMap = new Map();

  values.forEach((value) => {
    const topicValue = getTopicValue(value);

    if (!topicValue) return;

    const key = getCanonicalTopic(topicValue);

    if (!key || topicMap.has(key)) return;

    topicMap.set(key, topicValue);
  });

  return Array.from(topicMap.values()).sort((a, b) =>
    a.localeCompare(b)
  );
};

const TopicLaunchCard = memo(function TopicLaunchCard({
  item,
  index,
  onSelect,
  onFocus,
  onPointerIntent,
  position,
  isClone = false,
}) {
  const {
    icon: TopicIcon,
    label,
    description,
  } = getTopicVisualMeta(item, index);

  const isAllTopics =
    normalizeTopic(item) === 'all';
return (
  <button
    type="button"
    className={`topic-launch-card ${
      isAllTopics
        ? 'topic-launch-card-featured'
        : ''
    }`}
style={{
  left:
    typeof position.x === 'number'
      ? `${position.x}px`
      : position.x,
  top:
    typeof position.y === 'number'
      ? `${position.y}px`
      : position.y,
  width: `${position.width}px`,
  height: `${position.height}px`,
  '--topic-delay': `${Math.min(
    (index % 5) * 36,
    144
  )}ms`,
  '--topic-center-scale': 1,
  '--topic-center-opacity': 1,
  '--topic-center-lift': '0px',
}}
    onPointerDown={(event) => {
      event.stopPropagation();
      onPointerIntent?.(event);
    }}
    onClick={(event) => {
      event.preventDefault();
      event.stopPropagation();
      onSelect(item);
    }}
    onFocus={(event) => {
      if (!isClone) {
        onFocus?.(event.currentTarget);
      }
    }}
    aria-hidden={isClone || undefined}
    aria-label={
      isClone
        ? undefined
        : `Show ${item} posts`
    }
    tabIndex={isClone ? -1 : 0}
    data-topic-clone={isClone ? 'true' : 'false'}
    data-topic-selectable="true"
  >
      <span
        className="topic-launch-card-glow"
        aria-hidden="true"
      />

<span
  className="topic-launch-orb"
  aria-hidden="true"
>
  <TopicIcon
    size={30}
    strokeWidth={1.8}
  />
</span>

      <span className="topic-launch-copy">
        <span className="topic-launch-card-header">
          <strong>
            {isAllTopics
              ? 'Explore everything'
              : item}
          </strong>

          <ArrowRight
            size={17}
            strokeWidth={2.2}
            aria-hidden="true"
          />
        </span>

        <small>{label}</small>
        <em>{description}</em>
      </span>
    </button>
  );
});

const TopicPill = memo(function TopicPill({
  item,
  active,
  onSelect,
}) {
  const topicName =
    getTopicValue(item) || 'Topic';

  return (
  <button
  type="button"
  className={
    active
      ? 'topic-pill active'
      : 'topic-pill'
  }
  onPointerDown={(event) => {
    event.stopPropagation();
  }}
  onClick={(event) => {
    event.preventDefault();
    event.stopPropagation();
    onSelect(topicName);
  }}
  title={topicName}
  aria-pressed={active}
  aria-label={`Show ${topicName} posts`}
>
      <span>
        {topicName.charAt(0).toUpperCase()}
      </span>

      <strong>{topicName}</strong>
    </button>
  );
});

// Memoized image component for feed posts with lazy loading and IntersectionObserver
const FeedImage = memo(function FeedImage({
  src,
  alt,
  index,
}) {
  const imgRef = useRef(null);

  const [shouldLoad, setShouldLoad] = useState(
    index < FAST_IMAGE_LIMIT
  );

useEffect(() => {
  if (shouldLoad || !imgRef.current) {
    return undefined;
  }

  const observer = new IntersectionObserver(
    ([entry]) => {
      if (!entry.isIntersecting) return;

      setShouldLoad(true);
      observer.disconnect();
    },
    {
      rootMargin: IMAGE_PRELOAD_MARGIN,
      threshold: 0,
    }
  );

  observer.observe(imgRef.current);

  return () => observer.disconnect();
}, [shouldLoad]);

  return (
    <img
      ref={imgRef}
      src={shouldLoad ? src : undefined}
      data-src={src}
      alt={alt}
      loading={
        index < FAST_IMAGE_LIMIT ? 'eager' : 'lazy'
      }
      decoding="async"
      fetchPriority={
        index < FAST_IMAGE_LIMIT
          ? 'high'
          : shouldLoad
            ? 'auto'
            : 'low'
      }
      className="feed-image"
    />
  );
});
const FeedPostCard = memo(function FeedPostCard({
  post,
  index,
  creatorName,
  creatorId,
  postId,
  isSaved,
  translatedText,
  isTranslated,
  isTranslating,
  isExplaining,
  explanation,
  onTopicClick,
  onSave,
  onOpenPost,
  onOpenCreator,
  onComments,
  onExplain,
  onTranslateChange,
  onModerate,
  canModerate,
}) {
  const hasMedia = Boolean(post.videoUrl || post.imageUrl);
  const hasTranslation = Boolean(translatedText);
  const [actionsOpen, setActionsOpen] = useState(false);

  return (
    <article
      id={`post-${postId}`}
      className={`snap-post ${!post.imageUrl && !post.videoUrl ? 'no-media' : ''}`}
      onClick={() => onOpenPost(post, creatorName)}
      role="button"
      tabIndex={0}
      onKeyDown={(event) => {
        if (event.key === 'Enter' || event.key === ' ') {
          event.preventDefault();
          onOpenPost(post, creatorName);
        }
      }}
    >
      {hasMedia && (
        <div className="mini-media">
          {post.videoUrl ? (
            <video
              src={post.videoUrl}
              controls
              playsInline
              preload="none"
            />
          ) : (
            <FeedImage
              src={post.imageUrl}
              alt={post.title || 'Post media'}
              index={index}
            />
          )}
        </div>
      )}

      <div className="post-content">
<button
  type="button"
  className="post-topic clickable-topic"
  onClick={(event) => {
    event.stopPropagation();

    onTopicClick(
      getPostTopics(post)[0] || 'Smarty'
    );
  }}
>
  {getPostTopics(post)[0] || 'Smarty'}
</button>

        <div className="post-author-row">
        <div className="post-author">
          {creatorId ? (
            <Link
  to={`/creator/${encodeURIComponent(
    String(creatorId)
  )}`}
  className="creator-link"
  title={`Open ${creatorName}'s creator profile`}
  aria-label={`Open ${creatorName}'s creator profile`}
  onClick={(event) => {
    event.preventDefault();
    event.stopPropagation();
    onOpenCreator(creatorId, postId);
  }}
  state={{
    fromPostId: postId,
    creatorId,
    databaseAuthorId: creatorId,
    databaseAuthor: post.author || '',
    source: 'feed-author-link',
  }}
>
  {creatorName}
</Link>
          ) : (
            <span
              className="creator-link creator-link-disabled"
              title="Creator profile unavailable for this post"
              aria-label="Creator profile unavailable for this post"
            >
              {creatorName}
            </span>
          )}
        </div>

          {canModerate && (
            <div className="post-safety-actions">
              <button
                type="button"
                className="post-more-button"
                aria-label="Post safety options"
                aria-expanded={actionsOpen}
                onClick={(event) => {
                  event.stopPropagation();
                  setActionsOpen((current) => !current);
                }}
              >
                <MoreHorizontal size={18} strokeWidth={2} />
              </button>

              {actionsOpen && (
                <div
                  className="post-safety-menu"
                  role="menu"
                  onClick={(event) => event.stopPropagation()}
                >
                  <button
                    type="button"
                    role="menuitem"
                    onClick={() => {
                      setActionsOpen(false);
                      onModerate('report', post, creatorId, creatorName);
                    }}
                  >
                    <Flag size={16} strokeWidth={2} />
                    Report post
                  </button>
                  <button
                    type="button"
                    role="menuitem"
                    className="danger"
                    onClick={() => {
                      setActionsOpen(false);
                      onModerate('block', post, creatorId, creatorName);
                    }}
                  >
                    <UserX size={16} strokeWidth={2} />
                    Block user
                  </button>
                </div>
              )}
            </div>
          )}
        </div>

        <h1>{post.title}</h1>
        <p>{isTranslated && translatedText ? translatedText : post.body}</p>

        <div className="post-actions">
          <button
            type="button"
            className={isSaved ? 'icon-action-btn saved' : 'icon-action-btn'}
            disabled={!postId}
            onClick={(event) => {
              event.stopPropagation();
              onSave(postId, isSaved);
            }}
            title={isSaved ? 'Saved' : 'Save'}
            aria-label={isSaved ? 'Saved' : 'Save'}
          >
            <Bookmark size={16} strokeWidth={2.25} fill={isSaved ? 'currentColor' : 'none'} />
          </button>



          <button
            type="button"
            className="icon-action-btn"
            disabled={!postId}
            title="Comments"
            aria-label="Comments"
            onClick={(event) => {
              event.stopPropagation();
              onComments(postId);
            }}
          >
           <MessageCircle size={16} strokeWidth={2.25} />
          </button>

          <button
            type="button"
            className="icon-action-btn"
            title="Simplify"
            aria-label="Simplify"
            onClick={(event) => {
              event.stopPropagation();
              onExplain(post);
            }}
            disabled={isExplaining}
          >
            {isExplaining ? (
             <Loader2 size={16} strokeWidth={2.25} className="spin-icon" />
            ) : (
              <Bot size={16} strokeWidth={2.25} />
            )}
          </button>

          <select
            onClick={(event) => event.stopPropagation()}
            onChange={(event) => onTranslateChange(post, event.target.value)}
            value={isTranslated ? 'translated' : ''}
            className="translate-dropdown"
            disabled={isTranslating}
          >
            <option value="" disabled>
               {isTranslating ? 'Translating...' : 'Translate'}
            </option>
            {hasTranslation && <option value="original">Original</option>}
            {hasTranslation && isTranslated && (
              <option value="translated" disabled>
                Translated
              </option>
            )}
            <option value="Hindi">Hindi</option>
            <option value="Tamil">Tamil</option>
            <option value="Spanish">Spanish</option>
            <option value="French">French</option>
          </select>
        </div>

        {isTranslating && (
          <div className="ai-loading-box">
            <span className="ai-loader-dot"></span>
            <p>Translating...</p>
          </div>
        )}

        {hasTranslation && !isTranslating && !isTranslated && (
          <div className="translated-box">
            <strong>Translation ready</strong>
            <p>Select the translated language again to view it, or choose Original to go back.</p>
          </div>
        )}

        {isExplaining && (
          <div className="ai-loading-box">
            <span className="ai-loader-dot"></span>
            <p>Simplifying...</p>
          </div>
        )}

        {explanation && !isExplaining && (
          <div className="simple-explanation">
            <strong>Simplify</strong>
            <p>{explanation}</p>
          </div>
        )}

        <div className="post-learn-more-hint">
          Click to learn more about this
        </div>
      </div>
    </article>
  );
});

export default function FeedPage() {
  const { user } = useAuth();
  const wrappingTopicCanvasRef = useRef(false);

  const topicRevealFrameRef = useRef(null);
  const topicSnapTimerRef = useRef(null);
  const topicSnapReleaseTimerRef = useRef(null);
  const isTopicAutoCenteringRef = useRef(false);
  const reducedMotionRef = useRef(false);
  const topicEdgeLoadLockRef = useRef(false);
  const topicEdgeLoadTimerRef = useRef(null);
  const lastTopicCanvasPositionRef = useRef({
  left: null,
  top: null,
});
const launchTopicsLengthRef = useRef(0);
const topicDisplayLimitRef = useRef(INITIAL_TOPIC_LIMIT);
const topicDragLoadDistanceRef = useRef(0);
const touchGestureRef = useRef({
  startX: 0,
  startY: 0,
  moved: false,
});
const canvasDraggingRef = useRef(false);
const canvasAnimationFrameRef = useRef(null);
const pendingCanvasPositionRef = useRef({
  left: 0,
  top: 0,
});
  const { topic } = useParams();
  const navigate = useNavigate();
  const location = useLocation();
const routeTopic = useMemo(() => {
  const params =
    new URLSearchParams(
      location.search
    );

  return (
    params.get('topic') ||
    topic ||
    ''
  );
}, [location.search, topic]);
  const mountedRef = useRef(true);
  const highlightTimerRef = useRef(null);
  const highlightRemoveTimerRef = useRef(null);
  const requestedCreatorIdsRef = useRef(new Set());
  const toastTimerRef = useRef(null);
  const restoredFeedPositionRef = useRef(false);
const previousTopicCanvasLayoutRef = useRef({
  width: 0,
  height: 0,
  offsetX: 0,
  offsetY: 0,
});
  const {
    posts,
    loading,
    loadingMore,
    error,
    nextCursor,
    loadMore,
    refetch,
    refresh,
    reload,
    savePost,
    blockCreator,
  } = useFeed();
  const currentUserId = String(
    user?.userId || user?.sub || user?.id || ''
  ).trim();

  const canvasVelocityRef = useRef({
  x: 0,
  y: 0,
});

const canvasMomentumFrameRef = useRef(null);

const lastCanvasMoveTimeRef = useRef(0);

const loadMoreRef = useRef(null);
const feedLoadLockRef = useRef(false);
const topicCanvasRef = useRef(null);
const topicCardMetricsRef = useRef([]);
const feedRef = useRef(null);
const topicSearchLoadRef = useRef({
  topic: '',
  cursors: new Set(),
  loading: false,
});

const canvasDragRef = useRef({
  pointerId: null,
  startX: 0,
  startY: 0,
  lastX: 0,
  lastY: 0,
  scrollLeft: 0,
  scrollTop: 0,
  moved: false,
});
const suppressTopicClickRef = useRef(false);
  const [translations, setTranslations] = useState({});
  const [translating, setTranslating] = useState({});
  const [showTranslated, setShowTranslated] = useState({});
  const [selectedTopic, setSelectedTopic] = useState('');
  const [allTopics, setAllTopics] = useState([]);
  const [topicsLoading, setTopicsLoading] = useState(false);
  const [topicsError, setTopicsError] = useState('');
  const [topicsReloadKey, setTopicsReloadKey] = useState(0);
  const [canvasViewportWidth, setCanvasViewportWidth] = useState(
    () =>
      typeof window === 'undefined'
        ? 1280
        : window.innerWidth
  );
  const [showCanvasHint, setShowCanvasHint] = useState(
    () =>
      typeof window === 'undefined' ||
      localStorage.getItem(
        'smarty.topicCanvas.hasInteracted'
      ) !== 'true'
  );
  const [toast, setToast] = useState('');
  const [simpleExplanations, setSimpleExplanations] = useState({});
  const [explaining, setExplaining] = useState({});
  const [savedPostIds, setSavedPostIds] = useState({});
  const [creatorProfiles, setCreatorProfiles] = useState({});
  const [renderLimit, setRenderLimit] = useState(
    INITIAL_RENDER_LIMIT
  );
  const [topicDisplayLimit, setTopicDisplayLimit] = useState(
    INITIAL_TOPIC_LIMIT
  );
  const [isCanvasDragging, setIsCanvasDragging] = useState(false);
  const [moderationTarget, setModerationTarget] = useState(null);
  const [moderationReason, setModerationReason] = useState('');
  const [moderationDetails, setModerationDetails] = useState('');
  const [moderationSubmitting, setModerationSubmitting] = useState(false);


const stopCanvasMomentum = useCallback(() => {
  if (canvasMomentumFrameRef.current) {
    cancelAnimationFrame(
      canvasMomentumFrameRef.current
    );

    canvasMomentumFrameRef.current = null;
  }

  canvasVelocityRef.current = {
    x: 0,
    y: 0,
  };
}, []);

const dismissCanvasHint = useCallback(() => {
  setShowCanvasHint(false);

  try {
    localStorage.setItem(
      'smarty.topicCanvas.hasInteracted',
      'true'
    );
  } catch {
    // Storage can be unavailable in private browsing.
  }
}, []);

useEffect(() => {
  const motionPreference =
    window.matchMedia(
      '(prefers-reduced-motion: reduce)'
    );

  const updateMotionPreference = () => {
    reducedMotionRef.current =
      motionPreference.matches;
  };

  updateMotionPreference();
  motionPreference.addEventListener?.(
    'change',
    updateMotionPreference
  );

  return () => {
    motionPreference.removeEventListener?.(
      'change',
      updateMotionPreference
    );
  };
}, []);

const updateTopicCardDepth = useCallback(() => {
  const canvas = topicCanvasRef.current;

  if (!canvas) return;

  const viewportCenterX =
    canvas.scrollLeft + canvas.clientWidth / 2;

  const viewportCenterY =
    canvas.scrollTop + canvas.clientHeight / 2;

  const focusRadius = Math.max(
    260,
    Math.min(canvas.clientWidth, canvas.clientHeight) * 0.68
  );

  let cardMetrics = topicCardMetricsRef.current;

  if (cardMetrics.length === 0) {
    const cards = canvas.querySelectorAll('.topic-launch-card');
    const canvasRect = canvas.getBoundingClientRect();

    cardMetrics = Array.from(cards, (card) => {
      const cardRect = card.getBoundingClientRect();
      card.style.removeProperty('--topic-focus');

      return {
        card,
        centerX:
          canvas.scrollLeft +
          cardRect.left -
          canvasRect.left +
          cardRect.width / 2,
        centerY:
          canvas.scrollTop +
          cardRect.top -
          canvasRect.top +
          cardRect.height / 2,
      };
    });

    topicCardMetricsRef.current = cardMetrics;
  }

  const liveHorizontalRange = canvas.clientWidth / 2 + 240;
  const liveVerticalRange = canvas.clientHeight / 2 + 220;

  cardMetrics.forEach(({ card, centerX, centerY }) => {
    const deltaX = centerX - viewportCenterX;
    const deltaY = centerY - viewportCenterY;
    const isNearViewport =
      Math.abs(deltaX) <= liveHorizontalRange &&
      Math.abs(deltaY) <= liveVerticalRange;

    if (!isNearViewport) {
      if (card.dataset.topicDepthSignature === 'distant') return;

      card.dataset.topicDepthSignature = 'distant';
      card.dataset.topicDetail = 'low';
      card.dataset.topicCentered = 'false';
      card.style.setProperty('--topic-center-scale', '0.86');
      card.style.setProperty('--topic-center-opacity', '0.42');
      card.style.setProperty('--topic-center-lift', '0px');
      card.style.setProperty('--topic-edge-depth', '0px');
      card.style.setProperty('--topic-edge-tilt', '0deg');
      return;
    }

    if (card.dataset.topicDetail !== 'high') {
      card.dataset.topicDetail = 'high';
    }
    const horizontalDistance = Math.min(
      Math.abs(deltaX) / Math.max(canvas.clientWidth / 2, 1),
      1
    );
    const isWideDesktop = canvas.clientWidth >= 1100;
    const isTabletCanvas = canvas.clientWidth >= 700;
    const edgeCurveStart = isWideDesktop ? 0.34 : 0.5;
    const rawEdgeCurve = isTabletCanvas
      ? Math.max(
          0,
          (horizontalDistance - edgeCurveStart) / (1 - edgeCurveStart)
        )
      : 0;
    const easedEdgeCurve =
      rawEdgeCurve * rawEdgeCurve * (3 - 2 * rawEdgeCurve);
    const outsideFocusArea =
      Math.abs(deltaX) >= focusRadius ||
      Math.abs(deltaY) >= focusRadius;
    const normalizedDistance = outsideFocusArea
      ? 1
      : Math.min(
          Math.sqrt(deltaX * deltaX + deltaY * deltaY) / focusRadius,
          1
        );
    const rawFocus = reducedMotionRef.current
      ? 1
      : 1 - normalizedDistance;
    const easedFocus =
      rawFocus * rawFocus * (3 - 2 * rawFocus);

    // Fine-grained steps keep the depth response smooth without forcing
    // imperceptible style writes on every fractional pixel of movement.
    const focusStep = Math.round(easedFocus * 16);
    const edgeStep = Math.round(easedEdgeCurve * 8);
    const edgeSide = deltaX === 0 ? 0 : deltaX > 0 ? 1 : -1;
    const depthSignature = `${focusStep}:${edgeStep}:${edgeSide}`;

    if (card.dataset.topicDepthSignature === depthSignature) return;

    card.dataset.topicDepthSignature = depthSignature;
    card.dataset.topicFocusStep = String(focusStep);

    const focus = focusStep / 16;
    const edgeCurve = edgeStep / 8;
    const scale = 0.88 + focus * 0.22;
    const opacity = 0.64 + focus * 0.36;
    const lift = focus * -16;
    const edgeDepth = edgeCurve * (isWideDesktop ? -78 : -30);
    const edgeTilt = edgeSide * edgeCurve * (isWideDesktop ? -10 : -4);
    card.style.setProperty('--topic-center-scale', scale.toFixed(3));
    card.style.setProperty('--topic-center-opacity', opacity.toFixed(3));
    card.style.setProperty('--topic-center-lift', `${lift.toFixed(1)}px`);
    card.style.setProperty('--topic-edge-depth', `${edgeDepth.toFixed(1)}px`);
    card.style.setProperty('--topic-edge-tilt', `${edgeTilt.toFixed(1)}deg`);
    const isCentered = focus >= 0.66 ? 'true' : 'false';
    if (card.dataset.topicCentered !== isCentered) {
      card.dataset.topicCentered = isCentered;
    }
  });
}, []);
const wrapTopicCanvasPosition =
  useCallback(() => {
    const canvas = topicCanvasRef.current;

    if (
      !canvas ||
      wrappingTopicCanvasRef.current
    ) {
      return {
        horizontal: false,
        vertical: false,
      };
    }

    const maxScrollLeft = Math.max(
      0,
      canvas.scrollWidth -
        canvas.clientWidth
    );

    const maxScrollTop = Math.max(
      0,
      canvas.scrollHeight -
        canvas.clientHeight
    );

    if (
      maxScrollLeft === 0 &&
      maxScrollTop === 0
    ) {
      return {
        horizontal: false,
        vertical: false,
      };
    }

    let nextLeft = canvas.scrollLeft;
    let nextTop = canvas.scrollTop;
    let wrappedHorizontal = false;
    let wrappedVertical = false;
    const surface = canvas.querySelector(
      '.topic-canvas-surface'
    );
    const tileWidth = Math.max(
      1,
      (surface?.offsetWidth || canvas.scrollWidth) / 3
    );
    const tileHeight = Math.max(
      1,
      (surface?.offsetHeight || canvas.scrollHeight) / 3
    );
    const viewportCenterX =
      canvas.scrollLeft + canvas.clientWidth / 2;
    const viewportCenterY =
      canvas.scrollTop + canvas.clientHeight / 2;

    /*
     * Each neighbouring tile is an identical copy. Moving by exactly one
     * tile preserves the visible pixels, making the boundary crossing
     * visually continuous rather than an edge-to-edge teleport.
     */
    if (viewportCenterX < tileWidth) {
      nextLeft += tileWidth;
      wrappedHorizontal = true;
    } else if (viewportCenterX >= tileWidth * 2) {
      nextLeft -= tileWidth;
      wrappedHorizontal = true;
    }

    if (viewportCenterY < tileHeight) {
      nextTop += tileHeight;
      wrappedVertical = true;
    } else if (viewportCenterY >= tileHeight * 2) {
      nextTop -= tileHeight;
      wrappedVertical = true;
    }

    nextLeft = Math.min(maxScrollLeft, Math.max(0, nextLeft));
    nextTop = Math.min(maxScrollTop, Math.max(0, nextTop));

    if (
      !wrappedHorizontal &&
      !wrappedVertical
    ) {
      return {
        horizontal: false,
        vertical: false,
      };
    }

    wrappingTopicCanvasRef.current = true;
    canvas.classList.add('topic-canvas-wrapping');

    const previousLeft =
      canvas.scrollLeft;

    const previousTop =
      canvas.scrollTop;

    canvas.scrollTo({
      left: nextLeft,
      top: nextTop,
      behavior: 'auto',
    });

    if (canvasDraggingRef.current) {
      canvasDragRef.current.scrollLeft +=
        nextLeft - previousLeft;

      canvasDragRef.current.scrollTop +=
        nextTop - previousTop;
    }

    lastTopicCanvasPositionRef.current = {
      left: nextLeft,
      top: nextTop,
    };

    requestAnimationFrame(() => {
      wrappingTopicCanvasRef.current =
        false;

      requestAnimationFrame(() => {
        canvas.classList.remove(
          'topic-canvas-wrapping'
        );
      });
    });

    return {
      horizontal: wrappedHorizontal,
      vertical: wrappedVertical,
    };
  }, []);


const startCanvasMomentum = useCallback(() => {
  const canvas = topicCanvasRef.current;

  if (!canvas) return;

  if (canvasMomentumFrameRef.current) {
    cancelAnimationFrame(
      canvasMomentumFrameRef.current
    );
  }

  const animateMomentum = () => {
    const currentCanvas =
      topicCanvasRef.current;

    if (!currentCanvas) {
      canvasMomentumFrameRef.current =
        null;

      return;
    }

    const velocity =
      canvasVelocityRef.current;

    velocity.x *= 0.9;
    velocity.y *= 0.9;

    if (
      Math.abs(velocity.x) < 0.15 &&
      Math.abs(velocity.y) < 0.15
    ) {
      canvasVelocityRef.current = {
        x: 0,
        y: 0,
      };

      canvasMomentumFrameRef.current =
        null;

      return;
    }

    const maxLeft = Math.max(
      0,
      currentCanvas.scrollWidth -
        currentCanvas.clientWidth
    );

    const maxTop = Math.max(
      0,
      currentCanvas.scrollHeight -
        currentCanvas.clientHeight
    );

    const nextLeft = Math.min(
      maxLeft,
      Math.max(
        0,
        currentCanvas.scrollLeft -
          velocity.x
      )
    );

    const nextTop = Math.min(
      maxTop,
      Math.max(
        0,
        currentCanvas.scrollTop -
          velocity.y
      )
    );

    currentCanvas.scrollLeft =
      nextLeft;

    currentCanvas.scrollTop =
      nextTop;

    const wrapped =
      wrapTopicCanvasPosition();

    const reachedHorizontalEdge =
      !wrapped.horizontal &&
      (nextLeft <= 0 ||
        nextLeft >= maxLeft);

    const reachedVerticalEdge =
      !wrapped.vertical &&
      (nextTop <= 0 ||
        nextTop >= maxTop);

    if (reachedHorizontalEdge) {
      velocity.x = 0;
    }

    if (reachedVerticalEdge) {
      velocity.y = 0;
    }

    canvasMomentumFrameRef.current =
      requestAnimationFrame(
        animateMomentum
      );
  };

  canvasMomentumFrameRef.current =
    requestAnimationFrame(
      animateMomentum
    );
}, [wrapTopicCanvasPosition]);

const handleCanvasPointerDown = useCallback((event) => {
  if (
    event.pointerType !== 'mouse' ||
    event.button !== 0
  ) {
    return;
  }

  /*
   * Let cards receive normal desktop clicks.
   * Mouse dragging starts only from the canvas background.
   */
if (event.target.closest('.topic-launch-card')) {
  return;
}

  const canvas = topicCanvasRef.current;

  if (!canvas) return;
  stopCanvasMomentum();

lastCanvasMoveTimeRef.current =
  performance.now();

canvasVelocityRef.current = {
  x: 0,
  y: 0,
};
  canvasDraggingRef.current = true;
  suppressTopicClickRef.current = false;
  topicDragLoadDistanceRef.current = 0;

  canvasDragRef.current = {
    pointerId: event.pointerId,
    startX: event.clientX,
    startY: event.clientY,
    lastX: event.clientX,
    lastY: event.clientY,
    scrollLeft: canvas.scrollLeft,
    scrollTop: canvas.scrollTop,
    moved: false,
  };

  canvas.setPointerCapture?.(event.pointerId);
  setIsCanvasDragging(true);
}, [stopCanvasMomentum]);





const handleCanvasPointerMove = useCallback((event) => {
  if (event.pointerType !== 'mouse') {
    return;
  }

  const canvas = topicCanvasRef.current;

  if (
    !canvas ||
    !canvasDraggingRef.current ||
    canvasDragRef.current.pointerId !== event.pointerId
  ) {
    return;
  }

  const deltaX =
    event.clientX - canvasDragRef.current.startX;

  const deltaY =
    event.clientY - canvasDragRef.current.startY;

  const stepX =
    event.clientX - canvasDragRef.current.lastX;

  const stepY =
    event.clientY - canvasDragRef.current.lastY;

  const stepDistance = Math.hypot(stepX, stepY);
  const now = performance.now();

const elapsed = Math.max(
  8,
  now - lastCanvasMoveTimeRef.current
);

lastCanvasMoveTimeRef.current = now;

canvasVelocityRef.current = {
  x: (stepX / elapsed) * 16,
  y: (stepY / elapsed) * 16,
};

  canvasDragRef.current.lastX = event.clientX;
  canvasDragRef.current.lastY = event.clientY;

if (Math.hypot(deltaX, deltaY) > 6) {
  canvasDragRef.current.moved = true;
  suppressTopicClickRef.current = true;
}

const DRAG_SPEED = 0.82;
const maxLeft = Math.max(
  0,
  canvas.scrollWidth -
    canvas.clientWidth
);

const maxTop = Math.max(
  0,
  canvas.scrollHeight -
    canvas.clientHeight
);

pendingCanvasPositionRef.current = {
  left: Math.min(
    maxLeft,
    Math.max(
      0,
      canvasDragRef.current.scrollLeft -
        deltaX * DRAG_SPEED
    )
  ),

  top: Math.min(
    maxTop,
    Math.max(
      0,
      canvasDragRef.current.scrollTop -
        deltaY * DRAG_SPEED
    )
  ),
};

  if (!canvasAnimationFrameRef.current) {
    canvasAnimationFrameRef.current =
      requestAnimationFrame(() => {
        const currentCanvas =
          topicCanvasRef.current;

if (currentCanvas) {
  currentCanvas.scrollLeft =
    pendingCanvasPositionRef.current.left;

  currentCanvas.scrollTop =
    pendingCanvasPositionRef.current.top;
}

        canvasAnimationFrameRef.current = null;
      });
  }

  topicDragLoadDistanceRef.current += stepDistance;

  if (
    topicDragLoadDistanceRef.current >= 220 &&
    !topicEdgeLoadLockRef.current &&
    topicDisplayLimitRef.current <
      launchTopicsLengthRef.current
  ) {
    topicDragLoadDistanceRef.current = 0;
    topicEdgeLoadLockRef.current = true;

    setTopicDisplayLimit((current) => {
      const next = Math.min(
        current + TOPIC_BATCH_SIZE,
        launchTopicsLengthRef.current
      );

      topicDisplayLimitRef.current = next;
      return next;
    });

    if (topicEdgeLoadTimerRef.current) {
      clearTimeout(topicEdgeLoadTimerRef.current);
    }

    topicEdgeLoadTimerRef.current =
      window.setTimeout(() => {
        topicEdgeLoadLockRef.current = false;
        topicEdgeLoadTimerRef.current = null;
      }, 180);
  }
}, []);

const stopCanvasDragging = useCallback((event) => {
  if (event.pointerType !== 'mouse') {
    return;
  }

  const canvas = topicCanvasRef.current;

  canvasDraggingRef.current = false;
  topicDragLoadDistanceRef.current = 0;

  if (canvas?.hasPointerCapture?.(event.pointerId)) {
    canvas.releasePointerCapture(event.pointerId);
  }

  canvasDragRef.current.pointerId = null;

  if (canvasAnimationFrameRef.current) {
    cancelAnimationFrame(
      canvasAnimationFrameRef.current
    );

    canvasAnimationFrameRef.current = null;
  }
  setIsCanvasDragging(false);

  window.setTimeout(() => {
    suppressTopicClickRef.current = false;
    canvasDragRef.current.moved = false;
  }, 80);
}, []);

useEffect(() => {
  mountedRef.current = true;

  return () => {
    mountedRef.current = false;

    if (highlightTimerRef.current) {
      clearTimeout(highlightTimerRef.current);
    }

    if (highlightRemoveTimerRef.current) {
      clearTimeout(highlightRemoveTimerRef.current);
    }

    if (topicEdgeLoadTimerRef.current) {
      clearTimeout(topicEdgeLoadTimerRef.current);
      topicEdgeLoadTimerRef.current = null;
    }

    if (topicRevealFrameRef.current) {
      cancelAnimationFrame(topicRevealFrameRef.current);
      topicRevealFrameRef.current = null;
    }

    if (canvasAnimationFrameRef.current) {
      cancelAnimationFrame(canvasAnimationFrameRef.current);
      canvasAnimationFrameRef.current = null;
    }

    if (topicSnapTimerRef.current) {
      clearTimeout(topicSnapTimerRef.current);
      topicSnapTimerRef.current = null;
    }

  };
}, []);

  useEffect(() => {
    const params = new URLSearchParams(location.search);
    const targetPostId = params.get('postId');

    if (!targetPostId) return undefined;

    if (highlightTimerRef.current) clearTimeout(highlightTimerRef.current);
    if (highlightRemoveTimerRef.current) clearTimeout(highlightRemoveTimerRef.current);

    highlightTimerRef.current = window.setTimeout(() => {
      if (!mountedRef.current) return;

      const el = document.getElementById(`post-${targetPostId}`);
      if (el) {
        el.scrollIntoView({ behavior: 'smooth', block: 'center' });
        el.classList.add('highlight-post');

        highlightRemoveTimerRef.current = window.setTimeout(() => {
          el.classList.remove('highlight-post');
        }, 2000);
      }
    }, 450);

    return () => {
      if (highlightTimerRef.current) clearTimeout(highlightTimerRef.current);
      if (highlightRemoveTimerRef.current) clearTimeout(highlightRemoveTimerRef.current);
    };
  }, [location.search, posts.length]);

  const visiblePosts = useMemo(() => {
    const map = new Map();

    (posts || []).forEach((post) => {
      const postId = getPostId(post);
      if (!postId) return;

      const visibility = String(post.visibility || 'public').toLowerCase();

      const canShow =
        visibility === 'public' ||
        visibility === 'published' ||
        visibility === '' ||
        visibility === 'null';

      if (!canShow) return;

      if (!map.has(postId)) {
        map.set(postId, post);
      }
    });

    return Array.from(map.values()).sort((a, b) => getPostTime(b) - getPostTime(a));
  }, [posts]);


  useEffect(() => {
  let cancelled = false;

  async function loadTopics() {
    try {
      setTopicsLoading(true);

      const data = await postApi.getTopics();

      const nextTopics = Array.isArray(data)
        ? data
        : Array.isArray(data?.topics)
          ? data.topics
          : [];

      if (!cancelled && nextTopics.length > 0) {
        setAllTopics(uniqueTopicList(nextTopics));
      }
    } catch (err) {
      console.error('Could not load topics:', err);
    } finally {
      if (!cancelled) setTopicsLoading(false);
    }
  }

  loadTopics();

  return () => {
    cancelled = true;
  };
}, []);


  const handleTranslate = useCallback(async (post, lang = 'Hindi') => {
    const postId = getPostId(post);
    if (!postId || translating[postId]) return;

    try {
      setTranslating((prev) => ({ ...prev, [postId]: true }));

      const data = await postApi.translatePost({
        postId,
        title: post.title,
        body: post.body,
        targetLang: lang,
      });
      if (!mountedRef.current) return;

      const translation = data?.translation?.trim();

      if (!translation || translation === 'Translation not available right now.') {
        setTranslations((prev) => {
          const copy = { ...prev };
          delete copy[postId];
          return copy;
        });

        setShowTranslated((prev) => ({
          ...prev,
          [postId]: false,
        }));

        showToast('Translation failed. Check Lambda logs.');
        return;
      }

      setTranslations((prev) => ({
        ...prev,
        [postId]: translation,
      }));

      setShowTranslated((prev) => ({
        ...prev,
        [postId]: true,
      }));
    } catch (err) {
      console.error('Translate failed:', err);

      setTranslations((prev) => {
        const copy = { ...prev };
        delete copy[postId];
        return copy;
      });

      setShowTranslated((prev) => ({
        ...prev,
        [postId]: false,
      }));

      showToast('Translation failed');
    } finally {
      if (mountedRef.current) {
        setTranslating((prev) => ({ ...prev, [postId]: false }));
      }
    }
  }, [translating]);




const topics = useMemo(() => {
  if (allTopics.length > 0) {
    return ['All', ...allTopics];
  }

  return [
    'All',
    ...uniqueTopicList(
visiblePosts.flatMap((post) => {
  const postTopics =
    getPostTopics(post);

  return postTopics.length > 0
    ? postTopics
    : ['Smarty'];
})
    ),
  ];
}, [allTopics, visiblePosts]);

const launchTopics = useMemo(() => topics, [topics]);

useEffect(() => {
  if (selectedTopic) return;

  const fullTopicCount = launchTopics.length;

  setTopicDisplayLimit(fullTopicCount);
  topicDisplayLimitRef.current = fullTopicCount;
}, [selectedTopic, launchTopics.length]);

const visibleLaunchTopics = useMemo(
  () => launchTopics.slice(0, topicDisplayLimit),
  [launchTopics, topicDisplayLimit]
);

useEffect(() => {
  if (selectedTopic) return undefined;

  const canvas = topicCanvasRef.current;
  const updateViewportWidth = () => {
    setCanvasViewportWidth(
      canvas?.clientWidth || window.innerWidth
    );
  };

  updateViewportWidth();

  const resizeObserver =
    typeof ResizeObserver === 'undefined' || !canvas
      ? null
      : new ResizeObserver(updateViewportWidth);

  resizeObserver?.observe(canvas);
  window.addEventListener('resize', updateViewportWidth);

  return () => {
    resizeObserver?.disconnect();
    window.removeEventListener('resize', updateViewportWidth);
  };
}, [selectedTopic]);

useEffect(() => {
  launchTopicsLengthRef.current =
    launchTopics.length;
}, [launchTopics.length]);

useEffect(() => {
  topicDisplayLimitRef.current =
    topicDisplayLimit;
}, [topicDisplayLimit]);

const topicCanvasLayout = useMemo(
  () =>
    getTopicCanvasLayout(
      visibleLaunchTopics.length,
      canvasViewportWidth
    ),
  [visibleLaunchTopics.length, canvasViewportWidth]
);

const topicCanvasSurfaceStyle = useMemo(
  () => ({
    width: `${topicCanvasLayout.width * 3}px`,
    height: `${topicCanvasLayout.height * 3}px`,
    '--topic-tile-content-width': `${topicCanvasLayout.width}px`,
    '--topic-tile-content-height': `${topicCanvasLayout.height}px`,
  }),
  [
    topicCanvasLayout.height,
    topicCanvasLayout.width,
  ]
);

const filteredPosts = useMemo(() => {
  if (!selectedTopic) return [];

  if (areTopicsEquivalent(selectedTopic, 'All')) {
    return visiblePosts;
  }

  return visiblePosts.filter((post) => {
    const postTopics = getPostTopics(post);

    if (postTopics.length === 0) {
      return areTopicsEquivalent(selectedTopic, 'Smarty');
    }

    return postTopics.some((postTopic) =>
      areTopicsEquivalent(postTopic, selectedTopic)
    );
  });
}, [selectedTopic, visiblePosts]);

useEffect(() => {
  const normalizedSelectedTopic =
    getCanonicalTopic(selectedTopic);

  if (
    !normalizedSelectedTopic ||
    normalizedSelectedTopic === 'all'
  ) {
    topicSearchLoadRef.current = {
      topic: normalizedSelectedTopic,
      cursors: new Set(),
      loading: false,
    };

    return;
  }

  if (
    topicSearchLoadRef.current.topic !==
    normalizedSelectedTopic
  ) {
    topicSearchLoadRef.current = {
      topic: normalizedSelectedTopic,
      cursors: new Set(),
      loading: false,
    };
  }

  if (
    filteredPosts.length > 0 ||
    !nextCursor ||
    loading ||
    loadingMore ||
    topicSearchLoadRef.current.loading
  ) {
    return;
  }

  const cursorKey =
    typeof nextCursor === 'string'
      ? nextCursor
      : JSON.stringify(nextCursor);

  if (
    topicSearchLoadRef.current.cursors.has(cursorKey)
  ) {
    console.warn(
      'Stopped repeated topic cursor:',
      cursorKey
    );

    return;
  }

  topicSearchLoadRef.current.cursors.add(cursorKey);
  topicSearchLoadRef.current.loading = true;

  const requestedTopic = normalizedSelectedTopic;

  Promise.resolve(loadMore())
    .catch((loadError) => {
      console.error(
        'Could not load more posts for topic:',
        selectedTopic,
        loadError
      );
    })
    .finally(() => {
      if (
        topicSearchLoadRef.current.topic ===
        requestedTopic
      ) {
        topicSearchLoadRef.current.loading = false;
      }
    });
}, [
  selectedTopic,
  filteredPosts.length,
  nextCursor,
  loading,
  loadingMore,
  loadMore,
]);

useEffect(() => {
  if (!routeTopic) return;

  let decodedTopic = routeTopic;

  try {
    decodedTopic = decodeURIComponent(routeTopic);
  } catch {
    decodedTopic = routeTopic;
  }

  const matchingTopic = topics.find((item) =>
    areTopicsEquivalent(
      getTopicValue(item),
      decodedTopic
    )
  );

  const nextTopic =
    getTopicValue(matchingTopic) || decodedTopic;

  setSelectedTopic((currentTopic) => {
    if (
      areTopicsEquivalent(currentTopic, nextTopic)
    ) {
      return currentTopic;
    }

    return nextTopic;
  });

  setRenderLimit(INITIAL_RENDER_LIMIT);
}, [routeTopic, topics]);

  const renderedFeedPosts = useMemo(
    () => filteredPosts.slice(0, renderLimit),
    [filteredPosts, renderLimit]
  );

  useEffect(() => {
    const savedPostId = sessionStorage.getItem(FEED_POST_ID_STORAGE_KEY) || '';
    const savedRenderLimit = Number(sessionStorage.getItem(FEED_RENDER_LIMIT_STORAGE_KEY) || 0);

    if (!savedPostId || !filteredPosts.length || restoredFeedPositionRef.current) return;

    const savedPostIndex = filteredPosts.findIndex((post) => getPostId(post) === savedPostId);
    const neededRenderLimit = savedPostIndex >= 0
      ? savedPostIndex + 1
      : savedRenderLimit;

    if (neededRenderLimit > renderLimit) {
      setRenderLimit(Math.min(neededRenderLimit + RENDER_BATCH_SIZE, filteredPosts.length));
    }
  }, [filteredPosts, renderLimit]);




  useEffect(() => {
    if (restoredFeedPositionRef.current) return undefined;

    const savedScrollY = Number(sessionStorage.getItem(FEED_SCROLL_STORAGE_KEY) || 0);
    const savedPostId = sessionStorage.getItem(FEED_POST_ID_STORAGE_KEY) || '';

    if (!savedPostId || !filteredPosts.length || renderedFeedPosts.length === 0) {
      return undefined;
    }

    const savedPostIndex = filteredPosts.findIndex((post) => getPostId(post) === savedPostId);

    if (savedPostIndex >= renderedFeedPosts.length) {
      return undefined;
    }

    const timer = window.setTimeout(() => {
      if (!mountedRef.current) return;

      const savedPostElement = document.getElementById(`post-${savedPostId}`);

      if (!savedPostElement) return;

      restoredFeedPositionRef.current = true;

      savedPostElement.scrollIntoView({
        block: 'start',
        behavior: 'auto',
      });

      requestAnimationFrame(() => {
        requestAnimationFrame(() => {
          if (!mountedRef.current) return;

          if (Number.isFinite(savedScrollY) && savedScrollY > 0 && feedRef.current) {
            feedRef.current.scrollTop = savedScrollY;
            feedRef.current.scrollTo({
              top: savedScrollY,
              behavior: 'auto',
            });
          }
        });
      });
    }, 120);

    return () => clearTimeout(timer);
  }, [filteredPosts, renderedFeedPosts.length]);

  const renderedPostIdSet = useMemo(
    () => new Set(renderedFeedPosts.map((post) => getPostId(post)).filter(Boolean)),
    [renderedFeedPosts]
  );

  useEffect(() => {
    const savedPostId = sessionStorage.getItem(FEED_POST_ID_STORAGE_KEY) || '';

    if (savedPostId && !restoredFeedPositionRef.current) return;

    restoredFeedPositionRef.current = false;
    setRenderLimit(INITIAL_RENDER_LIMIT);
  },  [routeTopic, selectedTopic]);
  const indexOfPostInFeed = useCallback((feedPosts, targetPostId) => (
    feedPosts.findIndex((item) => getPostId(item) === targetPostId)
  ), []);

useEffect(() => {
  if (selectedTopic) return undefined;

  const canvas = topicCanvasRef.current;

  if (!canvas) return undefined;

  const frame = requestAnimationFrame(() => {
    canvas.scrollLeft = Math.max(
      0,
      (canvas.scrollWidth - canvas.clientWidth) / 2
    );

    canvas.scrollTop = Math.max(
      0,
      (canvas.scrollHeight - canvas.clientHeight) / 2
    );

    lastTopicCanvasPositionRef.current = {
      left: canvas.scrollLeft,
      top: canvas.scrollTop,
    };

previousTopicCanvasLayoutRef.current = {
  width: topicCanvasLayout.width,
  height: topicCanvasLayout.height,
  offsetX: topicCanvasLayout.offsetX,
  offsetY: topicCanvasLayout.offsetY,
};
  });

  return () => cancelAnimationFrame(frame);
}, [
  selectedTopic,
  topicCanvasLayout.width,
  topicCanvasLayout.height,
  topicCanvasLayout.offsetX,
  topicCanvasLayout.offsetY,
]);

useEffect(() => {
  const canvas = topicCanvasRef.current;

  if (!canvas || selectedTopic) {
    return undefined;
  }

  const previous =
    previousTopicCanvasLayoutRef.current;

  if (!previous.width || !previous.height) {
    previousTopicCanvasLayoutRef.current = {
      width: topicCanvasLayout.width,
      height: topicCanvasLayout.height,
      offsetX: topicCanvasLayout.offsetX,
      offsetY: topicCanvasLayout.offsetY,
    };

    return undefined;
  }

  const offsetShiftX =
    topicCanvasLayout.offsetX - previous.offsetX;

  const offsetShiftY =
    topicCanvasLayout.offsetY - previous.offsetY;

  previousTopicCanvasLayoutRef.current = {
    width: topicCanvasLayout.width,
    height: topicCanvasLayout.height,
    offsetX: topicCanvasLayout.offsetX,
    offsetY: topicCanvasLayout.offsetY,
  };

  if (offsetShiftX === 0 && offsetShiftY === 0) {
    return undefined;
  }

  const frame = requestAnimationFrame(() => {
    canvas.scrollLeft += offsetShiftX;
    canvas.scrollTop += offsetShiftY;

    lastTopicCanvasPositionRef.current = {
      left: canvas.scrollLeft,
      top: canvas.scrollTop,
    };
  });

  return () => cancelAnimationFrame(frame);
}, [
  selectedTopic,
  topicCanvasLayout.width,
  topicCanvasLayout.height,
  topicCanvasLayout.offsetX,
  topicCanvasLayout.offsetY,
]);

  useEffect(() => {
    const pruneByRenderedPosts = (current) => {
      let changed = false;
      const next = {};

      Object.entries(current).forEach(([postId, value]) => {
        if (renderedPostIdSet.has(postId)) {
          next[postId] = value;
        } else {
          changed = true;
        }
      });

      return changed ? next : current;
    };

    setTranslations(pruneByRenderedPosts);
    setShowTranslated(pruneByRenderedPosts);
    setTranslating(pruneByRenderedPosts);
    setSimpleExplanations(pruneByRenderedPosts);
    setExplaining(pruneByRenderedPosts);
    setSavedPostIds(pruneByRenderedPosts);
  }, [renderedPostIdSet]);

useEffect(() => {
  const target = loadMoreRef.current;
  const root = feedRef.current;

  if (!target || !root || !selectedTopic) {
    return undefined;
  }

  const observer = new IntersectionObserver(
    async ([entry]) => {
      if (
        !entry.isIntersecting ||
        loading ||
        loadingMore ||
        feedLoadLockRef.current
      ) {
        return;
      }

      feedLoadLockRef.current = true;

      try {
        /*
         * First reveal more posts that are already loaded in memory.
         */
        if (renderLimit < filteredPosts.length) {
          setRenderLimit((current) =>
            Math.min(
              current + RENDER_BATCH_SIZE,
              filteredPosts.length
            )
          );

          return;
        }

        /*
         * After all current posts are rendered, request the next API page.
         */
        if (nextCursor) {
          await loadMore();
        }
      } catch (loadError) {
        console.error(
          'Infinite feed load failed:',
          loadError
        );
      } finally {
        window.setTimeout(() => {
          feedLoadLockRef.current = false;
        }, 120);
      }
    },
    {
      root,
      rootMargin: '1200px 0px',
      threshold: 0.01,
    }
  );

  observer.observe(target);

  return () => {
    observer.disconnect();
  };
}, [
  selectedTopic,
  nextCursor,
  loadingMore,
  loading,
  loadMore,
  renderLimit,
  filteredPosts.length,
]);


useEffect(() => {
  if (!loadingMore) {
    feedLoadLockRef.current = false;
  }
}, [loadingMore, nextCursor]);



  const visibleCreatorIds = useMemo(
    () => [
      ...new Set(
        renderedFeedPosts
  .filter((post) => !isSystemGeneratedPost(post))
  .map((post) => getPostCreatorId(post))
  .filter(Boolean)
      ),
    ],
    [renderedFeedPosts]
  );

  useEffect(() => {
    const missingCreatorIds = visibleCreatorIds.filter(
      (id) => !creatorProfiles[id] && !requestedCreatorIdsRef.current.has(id)
    );

    if (missingCreatorIds.length === 0) return undefined;

    let cancelled = false;

    missingCreatorIds.forEach((id) => requestedCreatorIdsRef.current.add(id));

    async function loadCreatorProfiles() {
      const loadedProfiles = {};

      await Promise.allSettled(
        missingCreatorIds.map(async (creatorId) => {
          try {
            const profileResponse = await creatorApi.getProfile(creatorId);
            loadedProfiles[creatorId] = normalizeCreatorProfile(profileResponse);
          } catch (err) {
            requestedCreatorIdsRef.current.delete(creatorId);
            console.error('Could not load creator profile:', creatorId, err);
          }
        })
      );

      if (!cancelled && mountedRef.current && Object.keys(loadedProfiles).length > 0) {
        setCreatorProfiles((prev) => ({ ...prev, ...loadedProfiles }));
      }
    }

    loadCreatorProfiles();

    return () => {
      cancelled = true;
    };
  }, [visibleCreatorIds, creatorProfiles]);

  const showToast = useCallback((message, duration = 1200) => {
    if (toastTimerRef.current) {
      clearTimeout(toastTimerRef.current);
    }

    if (!mountedRef.current) return;

    setToast(message);

    toastTimerRef.current = setTimeout(() => {
      setToast('');
      toastTimerRef.current = null;
    }, duration);
  }, []);

  const openModerationDialog = useCallback(
    (mode, post, creatorId, creatorName) => {
      setModerationTarget({
        mode,
        post,
        postId: getPostId(post),
        creatorId: String(creatorId || '').trim(),
        creatorName: creatorName || 'this user',
      });
      setModerationReason('');
      setModerationDetails('');
    },
    []
  );

  const closeModerationDialog = useCallback(() => {
    if (moderationSubmitting) return;
    setModerationTarget(null);
    setModerationReason('');
    setModerationDetails('');
  }, [moderationSubmitting]);

  const submitModerationAction = useCallback(async () => {
    if (
      !moderationTarget?.creatorId ||
      !moderationTarget?.postId ||
      !moderationReason ||
      moderationSubmitting
    ) {
      return;
    }

    const reason = [
      moderationReason,
      moderationDetails.trim(),
    ]
      .filter(Boolean)
      .join(': ');

    setModerationSubmitting(true);

    try {
      if (moderationTarget.mode === 'report') {
        await chatApi.reportUser({
          reportedUserId: moderationTarget.creatorId,
          postId: moderationTarget.postId,
          contentType: 'post',
          source: 'feed-post-menu',
          reason,
        });

        showToast('Post reported. Thank you for helping keep Smarty safe.', 2600);
      } else {
        await chatApi.blockUser(moderationTarget.creatorId, {
          postId: moderationTarget.postId,
          contentType: 'post',
          source: 'feed-post-menu',
          reason,
        });

        // Remove all cached and rendered posts immediately, before any refresh.
        blockCreator(moderationTarget.creatorId);

        // Blocking from objectionable content also creates a moderation report,
        // so the developer receives the content and reason for review.
        try {
          await chatApi.reportUser({
            reportedUserId: moderationTarget.creatorId,
            postId: moderationTarget.postId,
            contentType: 'post',
            source: 'feed-block-action',
            reason: `User blocked: ${reason}`,
          });
        } catch (reportError) {
          // The block request already carries notifyDeveloper and content
          // context. Keep the user's safety action successful if the
          // secondary moderation-report request needs a backend retry.
          console.error('Secondary block report failed:', reportError);
        }

        showToast(
          `${moderationTarget.creatorName} was blocked and removed from your feed.`,
          3000
        );
      }

      setModerationTarget(null);
      setModerationReason('');
      setModerationDetails('');
    } catch (moderationError) {
      console.error('Moderation action failed:', moderationError);
      showToast(
        moderationError?.message || 'Could not complete that safety action.',
        2600
      );
    } finally {
      if (mountedRef.current) {
        setModerationSubmitting(false);
      }
    }
  }, [
    blockCreator,
    moderationDetails,
    moderationReason,
    moderationSubmitting,
    moderationTarget,
    showToast,
  ]);

useEffect(() => {
  const canvas = topicCanvasRef.current;

  if (!canvas || selectedTopic) {
    return undefined;
  }

const handleWheel = (event) => {
  stopCanvasMomentum();

  const dominantHorizontal =
    Math.abs(event.deltaX) >
    Math.abs(event.deltaY);

  const useHorizontal =
    dominantHorizontal ||
    event.shiftKey;

  if (useHorizontal) {
    event.preventDefault();

    canvas.scrollLeft +=
      dominantHorizontal
        ? event.deltaX
        : event.deltaY;
  }

};


  canvas.addEventListener(
    'wheel',
    handleWheel,
    { passive: false }
  );

return () => {
  canvas.removeEventListener(
    'wheel',
    handleWheel
  );
};
}, [
  selectedTopic,
  stopCanvasMomentum,
]);

  useEffect(() => {
    return () => {
      if (toastTimerRef.current) {
        clearTimeout(toastTimerRef.current);
        toastTimerRef.current = null;
      }
    };
  }, []);

  const handleSave = useCallback(async (postId, isCurrentlySaved = false) => {
    if (!postId) return;

    try {
      const data = await savePost(postId);
      if (!mountedRef.current) return;

      const nextSavedState = typeof data?.isSaved === 'boolean'
        ? data.isSaved
        : typeof data?.saved === 'boolean'
          ? data.saved
          : !isCurrentlySaved;

      setSavedPostIds((prev) => ({
        ...prev,
        [postId]: nextSavedState,
      }));

      showToast(nextSavedState ? 'Saved successfully 🔖' : 'Removed from saved');
    } catch (err) {
      console.error('Save toggle failed:', err);
      showToast('Bookmark update failed');
    }
  }, [savePost, showToast]);

  const handleExplain = useCallback(async (post) => {
    const postId = getPostId(post);
    if (!postId || explaining[postId]) return;

    if (simpleExplanations[postId]) {
      setSimpleExplanations((prev) => {
        const next = { ...prev };
        delete next[postId];
        return next;
      });
      return;
    }

    const cachedExplanation = getCachedExplanation(post);

    if (cachedExplanation) {
      setSimpleExplanations((prev) => ({
        ...prev,
        [postId]: cachedExplanation,
      }));
      return;
    }

    try {
      setExplaining((prev) => ({ ...prev, [postId]: true }));

      const data = await postApi.explainPost({
        postId,
        title: post.title,
        body: post.body,
      });
      if (!mountedRef.current) return;

      const explanationText =
        data?.explanation ||
        data?.aiExplanation ||
        data?.simpleExplanation ||
        data?.item?.aiExplanation ||
        data?.post?.aiExplanation ||
        'Could not simplify this post.';

      setSimpleExplanations((prev) => ({
        ...prev,
        [postId]: explanationText,
      }));
    } catch (err) {
      console.error('Simplify failed:', err);
      showToast('Could not simplify right now');
    } finally {
      if (mountedRef.current) {
        setExplaining((prev) => ({ ...prev, [postId]: false }));
      }
    }
  }, [explaining, simpleExplanations, showToast]);
  
const selectTopic = useCallback(
  (item, source = 'topic-pill') => {
    const nextTopic =
      getTopicValue(item) || 'All';

    const canonicalNextTopic =
      getCanonicalTopic(nextTopic);

    if (!canonicalNextTopic) {
      showToast('This topic is unavailable');
      return;
    }

    const isCurrentTopic = areTopicsEquivalent(
      selectedTopic,
      nextTopic
    );

    topicSearchLoadRef.current = {
      topic: canonicalNextTopic,
      cursors: new Set(),
      loading: false,
    };

    restoredFeedPositionRef.current = true;

    setSelectedTopic(nextTopic);
    setRenderLimit(INITIAL_RENDER_LIMIT);

    navigate(
      {
        pathname: '/feed',
        search: `?topic=${encodeURIComponent(
          nextTopic
        )}`,
      },
      {
        replace:
          source === 'topic-pill' &&
          isCurrentTopic,
        state: {
          selectedTopic: nextTopic,
          source,
        },
      }
    );

    requestAnimationFrame(() => {
      const feed = feedRef.current;

      if (!feed) return;

      feed.scrollTo({
        top: 0,
        behavior: 'auto',
      });
    });
  },
  [navigate, selectedTopic, showToast]
);

const handleTopicSelect = useCallback(
  (item) => {
    if (touchGestureRef.current.moved) {
      return;
    }

    selectTopic(item, 'topic-card');
  },
  [selectTopic]
);

const handleTopicCardPointerIntent = useCallback(() => {
  stopCanvasMomentum();

  // A fresh press is always direct selection intent, regardless of where the
  // card sits in the canvas. A real touch drag can still mark itself as moved.
  suppressTopicClickRef.current = false;
  canvasDragRef.current.moved = false;
  touchGestureRef.current.moved = false;
}, [stopCanvasMomentum]);

const handleTopicPillSelect = useCallback(
  (item) => {
    selectTopic(item, 'topic-pill');
  },
  [selectTopic]
);

const handleBackToTopics = useCallback(() => {
  setSelectedTopic('');
  setRenderLimit(INITIAL_RENDER_LIMIT);
  navigate('/feed');
}, [navigate]);

const handleFeedRetry = useCallback(() => {
  const retry = refetch || refresh || reload;

  if (typeof retry === 'function') {
    retry();
  }
}, [refetch, refresh, reload]);

const handleTopicClick = useCallback(
  (postTopic) => {
    if (!postTopic) return;

    selectTopic(postTopic, 'post-topic');
  },
  [selectTopic]
);
  // REMOVED handleAiDetails callback block

  const handleComments = useCallback(
    (postId) => {
      if (postId) navigate(`/comments/${postId}`);
    },
    [navigate]
  );

  const handleOpenCreator = useCallback(
  (creatorId, postId = '') => {
    const normalizedCreatorId = String(
      creatorId || ''
    ).trim();

    if (!normalizedCreatorId) {
      showToast('Creator profile unavailable');
      return;
    }

    navigate(
      `/creator/${encodeURIComponent(
        normalizedCreatorId
      )}`,
      {
        state: {
          fromPostId: postId,
          creatorId: normalizedCreatorId,
          databaseAuthorId:
            normalizedCreatorId,
          source: 'feed-author-link',
        },
      }
    );
  },
  [navigate, showToast]
);

  const handleOpenPost = useCallback(
    (post, creatorName) => {
      const postId = getPostId(post);
      if (!postId) return;

      const currentScrollY = feedRef.current?.scrollTop || window.scrollY || 0;
      restoredFeedPositionRef.current = false;
      sessionStorage.setItem(FEED_SCROLL_STORAGE_KEY, String(currentScrollY));
      sessionStorage.setItem(
        FEED_RENDER_LIMIT_STORAGE_KEY,
        String(Math.max(renderLimit, indexOfPostInFeed(filteredPosts, postId) + 1))
      );
      sessionStorage.setItem(FEED_POST_ID_STORAGE_KEY, postId);

      const {
        aiExplanation,
        simpleExplanation,
        explanation,
        explainText,
        simplifiedText,
        ...postForDetails
      } = post;

      navigate(`/post-ai/${postId}`, {
        state: {
          post: {
            ...postForDetails,
            id: postId,
            reelId: postId,
            aiDetailedExplanation: post.aiDetailedExplanation || '',
          },
          creatorName,
          feedScrollY: currentScrollY,
        },
      });
    },
    [filteredPosts, indexOfPostInFeed, navigate, renderLimit]
  );

  const handleTranslateChange = useCallback(
    (post, value) => {
      const postId = getPostId(post);

      if (value === 'original') {
        setShowTranslated((prev) => ({
          ...prev,
          [postId]: false,
        }));
        return;
      }

      handleTranslate(post, value);
    },
    [handleTranslate]
  );

const renderedTopics = useMemo(
  () =>
    launchTopics.map((item) => (
      <TopicPill
        key={getCanonicalTopic(item)}
        item={item}
        active={areTopicsEquivalent(
          selectedTopic,
          item
        )}
        onSelect={handleTopicPillSelect}
      />
    )),
  [
    handleTopicPillSelect,
    selectedTopic,
    launchTopics,
  ]
);

const renderedTopicCanvasTiles = useMemo(
  () =>
    Array.from({ length: 9 }, (_, tileIndex) => {
      const row = Math.floor(tileIndex / 3);
      const column = tileIndex % 3;
      const isPrimaryTile = tileIndex === 4;
      const tileKey = `${column - 1}:${row - 1}`;
      const horizontalTileOffset = column - 1;
      const verticalTileOffset = row - 1;
      const cloneBufferX = Math.min(
        topicCanvasLayout.width,
        Math.max(420, canvasViewportWidth * 0.58)
      );
      const cloneBufferY = Math.min(
        topicCanvasLayout.height,
        Math.max(
          420,
          (typeof window === 'undefined' ? 760 : window.innerHeight) * 0.62
        )
      );

      return (
        <div
          className={`topic-canvas-tile ${
            isPrimaryTile ? 'topic-canvas-tile-primary' : ''
          }`}
          key={`topic-tile-${tileKey}`}
          style={{
            left: `${column * (100 / 3)}%`,
            top: `${row * (100 / 3)}%`,
          }}
          aria-hidden={isPrimaryTile ? undefined : 'true'}
        >
          <div className="topic-canvas-tile-content">
            {visibleLaunchTopics.map((item, index) => {
              const position = getTopicCanvasPosition(
                index,
                canvasViewportWidth
              );
              const isOnlyTopic = visibleLaunchTopics.length === 1;
              const cardLeft = position.x + topicCanvasLayout.offsetX;
              const cardTop = position.y + topicCanvasLayout.offsetY;
              const cardRight = cardLeft + position.width;
              const cardBottom = cardTop + position.height;
              const isNearHorizontalSeam =
                horizontalTileOffset === 0 ||
                (horizontalTileOffset < 0
                  ? cardRight >= topicCanvasLayout.width - cloneBufferX
                  : cardLeft <= cloneBufferX);
              const isNearVerticalSeam =
                verticalTileOffset === 0 ||
                (verticalTileOffset < 0
                  ? cardBottom >= topicCanvasLayout.height - cloneBufferY
                  : cardTop <= cloneBufferY);

              // Neighbouring tiles only need cards that can actually enter the
              // viewport. The complete primary tile remains available.
              if (
                !isPrimaryTile &&
                (!isNearHorizontalSeam || !isNearVerticalSeam)
              ) {
                return null;
              }

              return (
                <TopicLaunchCard
                  key={`${tileKey}-${item}`}
                  item={item}
                  index={index}
                  isClone={!isPrimaryTile}
                  position={{
                    ...position,
                    x: isOnlyTopic
                      ? `calc(50% - ${position.width / 2}px)`
                      : position.x + topicCanvasLayout.offsetX,
                    y: isOnlyTopic
                      ? `calc(50% - ${position.height / 2}px)`
                      : position.y + topicCanvasLayout.offsetY,
                  }}
                  onSelect={handleTopicSelect}
                  onPointerIntent={handleTopicCardPointerIntent}
                />
              );
            })}
          </div>
        </div>
      );
    }),
  [
    handleTopicSelect,
    handleTopicCardPointerIntent,
    canvasViewportWidth,
    topicCanvasLayout.offsetX,
    topicCanvasLayout.offsetY,
    topicCanvasLayout.height,
    topicCanvasLayout.width,
    visibleLaunchTopics,
  ]
);

useEffect(() => {
  if (selectedTopic) return undefined;

  topicCardMetricsRef.current = [];

  const frame = requestAnimationFrame(() => {
    updateTopicCardDepth();
  });

  return () => cancelAnimationFrame(frame);
}, [
  selectedTopic,
  visibleLaunchTopics.length,
  topicCanvasLayout.width,
  topicCanvasLayout.height,
  updateTopicCardDepth,
]);

const handleTopicCanvasScroll =
  useCallback(() => {
    const canvas =
      topicCanvasRef.current;

    if (!canvas) return;

    canvas.classList.add('topic-canvas-scrolling');

    if (topicSnapTimerRef.current) {
      clearTimeout(topicSnapTimerRef.current);
    }

    topicSnapTimerRef.current = window.setTimeout(() => {
      canvas.classList.remove('topic-canvas-scrolling');
      topicSnapTimerRef.current = null;
    }, 110);

    if (!topicRevealFrameRef.current) {
      topicRevealFrameRef.current =
        requestAnimationFrame(() => {
          lastTopicCanvasPositionRef.current = {
            left: canvas.scrollLeft,
            top: canvas.scrollTop,
          };

          wrapTopicCanvasPosition();
          updateTopicCardDepth();
          topicRevealFrameRef.current = null;
        });
    }

    if (showCanvasHint) {
      dismissCanvasHint();
    }
  }, [
    dismissCanvasHint,
    showCanvasHint,
    updateTopicCardDepth,
    wrapTopicCanvasPosition,
  ]);

  const renderedPosts = useMemo(
    () => renderedFeedPosts.map((post, index) => {
      const postId = getPostId(post);
     const creatorId = isSystemGeneratedPost(post) ? '' : getPostCreatorId(post);
      const creatorProfile = creatorId ? creatorProfiles[creatorId] : null;
      const creatorName = getDisplayUsername(post, creatorProfile);
      const hasLocalSavedState = Object.prototype.hasOwnProperty.call(savedPostIds, postId);
      const isSaved = hasLocalSavedState
        ? Boolean(savedPostIds[postId])
        : Boolean(
            post.saved ||
              post.isSaved ||
              post.bookmarked ||
              post.isBookmarked ||
              post.savedByCurrentUser
          );

      // const cachedExplanation = getCachedExplanation(post); // Removed unused line
      const visibleExplanation = simpleExplanations[postId] || '';

      return (
<FeedPostCard
  key={`${postId}-${post.createdAtMs || post.updatedAtMs || post.createdAt || post.updatedAt || ''}`}
  post={post}
  index={index}
  postId={postId}
  isSaved={isSaved}
  creatorId={creatorId}
  creatorName={creatorName}
  translatedText={translations[postId]}
  isTranslated={Boolean(showTranslated[postId])}
  isTranslating={Boolean(translating[postId])}
  isExplaining={Boolean(explaining[postId])}
  explanation={visibleExplanation}
  onTopicClick={handleTopicClick}
  onSave={handleSave}
  onOpenPost={handleOpenPost}
  onOpenCreator={handleOpenCreator}
  onComments={handleComments}
  onExplain={handleExplain}
  onTranslateChange={handleTranslateChange}
  onModerate={openModerationDialog}
  canModerate={
    Boolean(creatorId) &&
    String(creatorId) !== currentUserId
  }
/>
      );
    }),
    [
      savedPostIds,
      creatorProfiles,
      explaining,
      renderedFeedPosts,
handleOpenPost,
handleOpenCreator,
handleComments,
      currentUserId,
      handleExplain,
      handleSave,
      handleTopicClick,
      handleTranslateChange,
      openModerationDialog,
      showTranslated,
      simpleExplanations,
      translating,
      translations,
    ]
  );

  return (
    <main
      ref={feedRef}
      className={`snap-feed-page ${
        selectedTopic ? 'has-inner-feed' : ''
      }`}
      style={{ overscrollBehaviorY: 'auto' }}
    >


      {toast && <div className="success-toast">{toast}</div>}

      {moderationTarget && (
        <div
          className="moderation-dialog-backdrop"
          role="presentation"
          onClick={closeModerationDialog}
        >
          <section
            className="moderation-dialog"
            role="dialog"
            aria-modal="true"
            aria-labelledby="moderation-dialog-title"
            onClick={(event) => event.stopPropagation()}
          >
            <header>
              <div>
                <span>Safety action</span>
                <h2 id="moderation-dialog-title">
                  {moderationTarget.mode === 'report'
                    ? 'Report this post'
                    : `Block ${moderationTarget.creatorName}`}
                </h2>
              </div>
              <button
                type="button"
                className="moderation-dialog-close"
                aria-label="Close"
                disabled={moderationSubmitting}
                onClick={closeModerationDialog}
              >
                <X size={18} strokeWidth={2} />
              </button>
            </header>

            <p>
              {moderationTarget.mode === 'report'
                ? 'Tell us what is wrong. The post and its creator will be sent to Smarty for moderation review.'
                : 'This user and all of their posts will disappear from your feed immediately. The selected post will also be sent to Smarty for review.'}
            </p>

            <fieldset>
              <legend>Reason</legend>
              <div className="moderation-reasons">
                {MODERATION_REASONS.map((reason) => (
                  <label key={reason}>
                    <input
                      type="radio"
                      name="moderation-reason"
                      value={reason}
                      checked={moderationReason === reason}
                      disabled={moderationSubmitting}
                      onChange={() => setModerationReason(reason)}
                    />
                    <span>{reason}</span>
                  </label>
                ))}
              </div>
            </fieldset>

            <label className="moderation-details">
              Additional details <span>Optional</span>
              <textarea
                value={moderationDetails}
                maxLength={500}
                disabled={moderationSubmitting}
                placeholder="Add context for the moderation team"
                onChange={(event) => setModerationDetails(event.target.value)}
              />
            </label>

            <div className="moderation-dialog-actions">
              <button
                type="button"
                className="secondary"
                disabled={moderationSubmitting}
                onClick={closeModerationDialog}
              >
                Cancel
              </button>
              <button
                type="button"
                className={
                  moderationTarget.mode === 'block'
                    ? 'danger'
                    : 'primary'
                }
                disabled={!moderationReason || moderationSubmitting}
                onClick={submitModerationAction}
              >
                {moderationSubmitting
                  ? 'Submitting...'
                  : moderationTarget.mode === 'report'
                    ? 'Submit report'
                    : 'Block and remove'}
              </button>
            </div>
          </section>
        </div>
      )}

{!selectedTopic && (
  <section
    className="topic-launch-screen"
    aria-label="Choose a learning topic"
  >
    <nav className="topic-canvas-navbar" aria-label="Smarty topic navigation">
  <SmartyBrand
    className="topic-canvas-brand"
    tagline="Learn · Share · Grow"
  />

  <span className="topic-canvas-nav-label">
    Explore topics
  </span>
</nav>

<div className="topic-scroll-hint" aria-hidden="true">
  <span className="topic-scroll-hint-icon">
    <ArrowRight size={14} strokeWidth={2.2} />
  </span>

  <span>Swipe or drag to explore</span>
</div>
    <div
      className="topic-launch-backdrop"
      aria-hidden="true"
    >
      <span className="topic-launch-ambient topic-launch-ambient-one" />
      <span className="topic-launch-ambient topic-launch-ambient-two" />
      <span className="topic-launch-grid-lines" />
    </div>

    <div className="topic-launch-shell">
      <header className="topic-launch-hero">
        <div className="topic-launch-badge">


        </div>

        {/* <h1>
          What do you want to
          <span> learn?</span>
        </h1> */}


      </header>

      <div className="topic-launch-content">
        <div className="topic-launch-section-heading">
          <div>
            <span>Topics</span>
            <h2>Choose one to begin</h2>
          </div>
        </div>

        {(loading || topicsLoading) &&
        launchTopics.length === 0 ? (
          <div
            className="topic-launch-loading"
            role="status"
            aria-live="polite"
          >
            <Loader2
              size={20}
              strokeWidth={2.25}
              className="spin-icon"
            />

            <span>Loading topics...</span>
          </div>
        ) : (
          <>
<div
  ref={topicCanvasRef}
  className={`topic-canvas-viewport ${
    isCanvasDragging
      ? 'topic-canvas-dragging'
      : ''
  }`}
  onScroll={handleTopicCanvasScroll}
  onTouchStart={(event) => {
    const canvas = topicCanvasRef.current;
    const touch = event.touches?.[0];

    if (!canvas || !touch) return;

    touchGestureRef.current = {
      startX: touch.clientX,
      startY: touch.clientY,
      moved: false,
    };

    canvasDragRef.current.moved = false;

    lastTopicCanvasPositionRef.current = {
      left: canvas.scrollLeft,
      top: canvas.scrollTop,
    };
  }}
  onTouchMove={(event) => {
    const touch = event.touches?.[0];

    if (!touch) return;

    const deltaX =
      touch.clientX -
      touchGestureRef.current.startX;

    const deltaY =
      touch.clientY -
      touchGestureRef.current.startY;

    if (Math.hypot(deltaX, deltaY) > 8) {
      touchGestureRef.current.moved = true;
      canvasDragRef.current.moved = true;
    }
  }}
  onTouchEnd={() => {
    window.setTimeout(() => {
      touchGestureRef.current.moved = false;
      canvasDragRef.current.moved = false;
    }, 80);
  }}
onPointerDown={handleCanvasPointerDown}
onPointerMove={handleCanvasPointerMove}
onPointerUp={stopCanvasDragging}
onPointerCancel={stopCanvasDragging}
onLostPointerCapture={(event) => {
  if (event.pointerType === 'mouse') {
    canvasDraggingRef.current = false;
    canvasDragRef.current.pointerId = null;
    canvasDragRef.current.moved = false;
suppressTopicClickRef.current = false;
    setIsCanvasDragging(false);
  }
}}
>
<div
  className="topic-canvas-surface"
style={topicCanvasSurfaceStyle}
>
  {renderedTopicCanvasTiles}
</div>
</div>


          </>
        )}
      </div>
    </div>
  </section>
)}

      {selectedTopic && (
        <header className="feed-inner-header">
          <div className="feed-inner-heading">
            <button
              type="button"
              className="feed-inner-back"
              onClick={handleBackToTopics}
              aria-label="Back to topics"
            >
              <ArrowLeft size={17} strokeWidth={2} />
              <span>Topics</span>
            </button>

            <div className="feed-inner-title">
              <h1>{selectedTopic}</h1>
              <p>
                {loading
                  ? 'Loading posts'
                  : error
                    ? 'Feed unavailable'
                    : `${filteredPosts.length}${nextCursor ? '+' : ''} ${
                        filteredPosts.length === 1 ? 'post' : 'posts'
                      }`}
              </p>
            </div>
          </div>

          <nav
            className="feed-inner-topics mobile-topic-scroll"
            role="tablist"
            aria-label="Select feed topic"
          >
            {renderedTopics}
          </nav>
        </header>
      )}

{selectedTopic && loading && filteredPosts.length === 0 && (
  <div className="feed-inner-loading">
    <FeedSkeleton />
  </div>
)}

{selectedTopic && error && (
  <div
    className="feed-inner-state feed-inner-error"
    role="alert"
  >
    <span className="feed-inner-state-icon" aria-hidden="true">
      <RefreshCw size={20} strokeWidth={1.8} />
    </span>
    <span className="feed-inner-state-kicker">Connection problem</span>
    <h2>We couldn't load this topic.</h2>
    <p>{error || 'The feed is temporarily unavailable.'}</p>

    <div className="feed-inner-state-actions">
      <button type="button" onClick={handleFeedRetry}>
        Try again
      </button>
      <button
        type="button"
        className="secondary"
        onClick={handleBackToTopics}
      >
        Browse topics
      </button>
    </div>
  </div>
)}

{selectedTopic &&
  !loading &&
  !loadingMore &&
  !error &&
  filteredPosts.length === 0 &&
  !nextCursor && (
    <div className="feed-inner-state">
      <span className="feed-inner-state-icon" aria-hidden="true">
        <Compass size={20} strokeWidth={1.8} />
      </span>
      <span className="feed-inner-state-kicker">Nothing here yet</span>
      <h2>No posts in {selectedTopic}.</h2>
      <p>Choose another topic or check back later.</p>
      <button type="button" onClick={handleBackToTopics}>
        Browse topics
      </button>
    </div>
  )}

{selectedTopic &&
  !loading &&
  !error &&
  filteredPosts.length === 0 &&
  nextCursor && (
    <p className="feed-status feed-inner-status">
      Loading topic posts...
    </p>
  )}

{selectedTopic && (
  <section className="snap-feed">
    {renderedPosts}

    <div
      ref={loadMoreRef}
      className="feed-load-trigger"
      aria-hidden="true"
    />
  </section>
)}

{selectedTopic &&
  (loadingMore ||
    renderLimit < filteredPosts.length) && (
    <p className="feed-status">
      Loading more posts...
    </p>
  )}
    </main>
  );
}

function getTopicCanvasPosition(index, viewportWidth) {
const resolvedViewportWidth =
  Number.isFinite(viewportWidth)
    ? viewportWidth
    : typeof window !== 'undefined'
      ? window.innerWidth
      : 1280;
const isDesktop = resolvedViewportWidth >= 760;
const isWideDesktop = resolvedViewportWidth >= 1100;
const columns = isWideDesktop ? 5 : isDesktop ? 4 : 3;
const width = isDesktop ? 168 : 146;
const height = isDesktop ? 132 : 120;
const gapX = isWideDesktop ? 232 : isDesktop ? 64 : 44;
const gapY = isWideDesktop ? 178 : isDesktop ? 58 : 46;
const column = index % columns;
const row = Math.floor(index / columns);

return {
  width,
  height,
  x: column * (width + gapX),
  y: row * (height + gapY),
};
}



function getTopicCanvasLayout(topicCount, viewportWidth) {
  const resolvedViewportWidth =
    Number.isFinite(viewportWidth)
      ? viewportWidth
      : typeof window !== 'undefined'
        ? window.innerWidth
        : 1280;
  const isDesktop = resolvedViewportWidth >= 760;
  const isWideDesktop = resolvedViewportWidth >= 1100;
  const edgePaddingX = isWideDesktop ? 116 : isDesktop ? 32 : 22;
  const edgePaddingY = isWideDesktop ? 89 : isDesktop ? 29 : 23;

  const cards = Array.from(
    { length: topicCount },
    (_, index) => ({
      index,
      ...getTopicCanvasPosition(index, resolvedViewportWidth),
    })
  );

  if (cards.length === 0) {
    return {
      width: 800,
      height: 700,
      offsetX: 0,
      offsetY: 0,
    };
  }

  const minX = Math.min(
    ...cards.map((card) => card.x)
  );

  const minY = Math.min(
    ...cards.map((card) => card.y)
  );

  const maxX = Math.max(
    ...cards.map(
      (card) => card.x + card.width
    )
  );

  const maxY = Math.max(
    ...cards.map(
      (card) => card.y + card.height
    )
  );

  return {
    width:
      maxX -
      minX +
      edgePaddingX * 2,

    height:
      maxY -
      minY +
      edgePaddingY * 2,

    offsetX:
      edgePaddingX - minX,

    offsetY:
      edgePaddingY - minY,
  };
}
