import { memo, useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Link, useLocation, useNavigate, useParams } from 'react-router-dom';
import {
  ArrowRight,
  Bookmark,
  MessageCircle,
  Bot,
  Loader2,
  Sparkles,
  Globe2,
  Brain,
  Microscope,
  Cpu,
  Code2,
  TrendingUp,
  HeartPulse,
  GraduationCap,
  Scale,
  Compass,
  Rocket,
  MoonStar,
  Lightbulb,
} from 'lucide-react';
import { postApi, creatorApi } from '../api/client';
import FeedSkeleton from '../components/FeedSkeleton';
import useFeed from '../hooks/useFeed';
import './FeedPage.css';

const normalizeTopic = (value) =>
  String(value || '')
    .normalize('NFKD')
    .toLowerCase()
    .trim()
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');

const TOPIC_ALIASES = new Map([
  ['ai', 'artificial-intelligence'],
  ['artificial-intelligence', 'artificial-intelligence'],
  ['tech', 'technology'],
  ['technology', 'technology'],
  ['programming', 'coding'],
  ['software-development', 'coding'],
  ['coding', 'coding'],
  ['mental-health', 'psychology'],
]);

const getCanonicalTopic = (value) => {
  const normalized = normalizeTopic(value);

  return TOPIC_ALIASES.get(normalized) || normalized;
};

const areTopicsEquivalent = (left, right) => {
  const normalizedLeft = getCanonicalTopic(left);
  const normalizedRight = getCanonicalTopic(right);

  return Boolean(
    normalizedLeft &&
      normalizedRight &&
      normalizedLeft === normalizedRight
  );
};

const getTopicValue = (value) => {
  if (value && typeof value === 'object') {
    return String(
      value.name ||
        value.label ||
        value.title ||
        value.topic ||
        value.topicName ||
        value.slug ||
        value.id ||
        ''
    ).trim();
  }

  return String(value || '').trim();
};

const getPostTopics = (post) => {
  const rawValues = [
    post?.topic,
    post?.topics,
    post?.category,
    post?.categories,
    post?.roomName,
    post?.subject,
    post?.tags,
  ];

  return rawValues
    .flatMap((value) => {
      if (Array.isArray(value)) {
        return value;
      }

      if (
        typeof value === 'string' &&
        value.includes(',')
      ) {
        return value.split(',');
      }

      return [value];
    })
    .map(getTopicValue)
    .filter(Boolean);
};

const getPostId = (post) => post?.reelId || post?.id || '';

const getPostTime = (post) => Number(post?.createdAtMs || post?.updatedAtMs || post?.createdAt || post?.updatedAt || post?.timestamp || 0);

const normalizeCreatorProfile = (value) => value?.profile || value?.user || value || null;


const INITIAL_RENDER_LIMIT = 10;
const RENDER_BATCH_SIZE = 8;

const INITIAL_TOPIC_LIMIT = 12;
const TOPIC_BATCH_SIZE = 4;
const FAST_IMAGE_LIMIT = 4;
const IMAGE_PRELOAD_MARGIN = '900px';
const FEED_SCROLL_STORAGE_KEY = 'smarty.feed.scrollY';
const FEED_RENDER_LIMIT_STORAGE_KEY = 'smarty.feed.renderLimit';
const FEED_POST_ID_STORAGE_KEY = 'smarty.feed.postId';

const getPostCreatorId = (post) => {
  const creatorId =
    post?.creatorId ||
    post?.creatorID ||
    post?.creator_id ||
    post?.authorId ||
    post?.authorID ||
    post?.author_id ||
    post?.userId ||
    post?.userID ||
    post?.user_id ||
    post?.author?.id ||
    post?.author?.userId ||
    post?.creator?.id ||
    post?.creator?.userId ||
    post?.user?.id ||
    post?.user?.userId ||
    '';

  return String(creatorId || '').trim();
};

const isSystemGeneratedPost = (post) => {
  const authorId = String(
    post?.authorId ||
    post?.authorID ||
    post?.author_id ||
    ''
  ).trim().toLowerCase();

  const authorName = String(
    post?.author ||
    post?.creatorName ||
    post?.authorName ||
    ''
  ).trim().toLowerCase();

  return Boolean(
    post?.isAutoGenerated ||
    post?.isSystemGenerated ||
    authorId === 'smarty-ai' ||
    authorName === 'smarty ai' ||
    authorName === 'smarty-ai'
  );
};




const getDisplayUsername = (post, creatorProfile = null) => {
  const profile = creatorProfile?.profile || creatorProfile?.user || creatorProfile || {};

  const databasePostNames = [
    post.creatorName,
    post.authorName,
    post.author,
    post.creatorEmail,
    post.authorEmail,
    post.email,
    post.creatorUsername,
    post.authorUsername,
    post.username,
    post.userName,
    post.displayName,
  ];

  const profileNames = [
    profile.username,
    profile.userName,
    profile.displayName,
    profile.name,
    profile.email,
  ];

  const nestedPostNames = [
    post.author?.username,
    post.author?.userName,
    post.author?.displayName,
    post.author?.name,
    post.author?.email,
    post.creator?.username,
    post.creator?.userName,
    post.creator?.displayName,
    post.creator?.name,
    post.creator?.email,
    post.user?.username,
    post.user?.userName,
    post.user?.displayName,
    post.user?.name,
    post.user?.email,
  ];

  const blockedValues = new Set([
    '',
    'null',
    'undefined',
    'none',
    'post',
    'creator',
    'unknown',
  ]);

  const formatName = (value) => {
    const text = String(value || '').trim();
    if (!text || blockedValues.has(text.toLowerCase())) return '';

    if (text.includes('@')) {
      return text.split('@')[0] || 'user';
    }

    return text;
  };

  const pickName = (values) => {
    for (const value of values) {
      const text = formatName(value);
      if (text) return text;
    }
    return '';
  };

  return pickName(databasePostNames) || pickName(profileNames) || pickName(nestedPostNames) || 'user';
};

const getCachedExplanation = (post) => {
  const value =
    post?.aiExplanation ||
    post?.simpleExplanation ||
    post?.explanation ||
    post?.explainText ||
    post?.simplifiedText ||
    '';

  const text = String(value || '').trim();
  return text && text.toLowerCase() !== 'null' && text.toLowerCase() !== 'undefined'
    ? text
    : '';
};

const getTopicVisualMeta = (topicName, index = 0) => {
  const normalized = normalizeTopic(topicName);

  const topicPalettes = {
    all: {
      icon: Globe2,
      label: 'Everything',
      description: 'Explore the full Smarty feed',
    },

    psychology: {
      icon: Brain,
      label: 'Mind Lab',
      description: 'Human behaviour, cognition, and mental health',
    },

    science: {
      icon: Microscope,
      label: 'Discovery Mode',
      description: 'Experiments, facts, and curiosity',
    },

    technology: {
      icon: Cpu,
      label: 'Future Stack',
      description: 'AI, cloud, apps, and modern tools',
    },

    coding: {
      icon: Code2,
      label: 'Build Mode',
      description: 'Programming, projects, and engineering',
    },

    business: {
      icon: TrendingUp,
      label: 'Growth Room',
      description: 'Startups, strategy, and money',
    },

    health: {
      icon: HeartPulse,
      label: 'Wellness Hub',
      description: 'Body, lifestyle, and care',
    },

    education: {
      icon: GraduationCap,
      label: 'Study Zone',
      description: 'Concepts, revision, and learning',
    },

    law: {
      icon: Scale,
      label: 'Case Mode',
      description: 'Rules, rights, and legal reasoning',
    },
  };

  const fallbackTopics = [
    {
      icon: Sparkles,
      label: 'Smart Pick',
      description: 'Fresh ideas selected for you',
    },
    {
      icon: Rocket,
      label: 'Deep Dive',
      description: 'Explore this learning lane',
    },
    {
      icon: MoonStar,
      label: 'Focus Flow',
      description: 'Calm, focused topic discovery',
    },
    {
      icon: Lightbulb,
      label: 'Idea Spark',
      description: 'Quick knowledge worth saving',
    },
  ];

  return (
    topicPalettes[normalized] ||
    fallbackTopics[index % fallbackTopics.length]
  );
};

const uniqueTopicList = (values = []) => {
  const topicMap = new Map();

  values.forEach((value) => {
    const topicValue = getTopicValue(value);

    if (!topicValue) return;

    const key = getCanonicalTopic(topicValue);

    if (!key || topicMap.has(key)) return;

    topicMap.set(key, topicValue);
  });

  return Array.from(topicMap.values()).sort((a, b) =>
    a.localeCompare(b)
  );
};

const TopicLaunchCard = memo(function TopicLaunchCard({
  item,
  index,
  onSelect,
  position,
}) {
  const {
    icon: TopicIcon,
    label,
    description,
  } = getTopicVisualMeta(item, index);

  const isAllTopics =
    normalizeTopic(item) === 'all';
return (
  <button
    type="button"
    className={`topic-launch-card ${
      isAllTopics
        ? 'topic-launch-card-featured'
        : ''
    }`}
style={{
  left: `${position.x}px`,
  top: `${position.y}px`,
  width: `${position.width}px`,
  height: `${position.height}px`,
  '--topic-delay': `${Math.min(
    (index % 5) * 36,
    144
  )}ms`,
  '--topic-center-scale': 1,
  '--topic-center-opacity': 1,
  '--topic-center-lift': '0px',
  '--topic-center-blur': '0px',
}}
    onPointerDown={(event) => {
      event.stopPropagation();
    }}
    onClick={(event) => {
      event.preventDefault();
      event.stopPropagation();
      onSelect(item);
    }}
    aria-label={`Show ${item} posts`}
  >
      <span
        className="topic-launch-card-glow"
        aria-hidden="true"
      />

<span
  className="topic-launch-orb"
  aria-hidden="true"
>
  <TopicIcon
    size={30}
    strokeWidth={1.8}
  />
</span>

      <span className="topic-launch-copy">
        <span className="topic-launch-card-header">
          <strong>
            {isAllTopics
              ? 'Explore everything'
              : item}
          </strong>

          <ArrowRight
            size={17}
            strokeWidth={2.2}
            aria-hidden="true"
          />
        </span>

        <small>{label}</small>
        <em>{description}</em>
      </span>
    </button>
  );
});

const TopicPill = memo(function TopicPill({
  item,
  active,
  onSelect,
}) {
  const topicName =
    getTopicValue(item) || 'Topic';

  return (
  <button
  type="button"
  className={
    active
      ? 'topic-pill active'
      : 'topic-pill'
  }
  onPointerDown={(event) => {
    event.stopPropagation();
  }}
  onClick={(event) => {
    event.preventDefault();
    event.stopPropagation();
    onSelect(topicName);
  }}
  title={topicName}
  aria-pressed={active}
  aria-label={`Show ${topicName} posts`}
>
      <span>
        {topicName.charAt(0).toUpperCase()}
      </span>

      <strong>{topicName}</strong>
    </button>
  );
});

// Memoized image component for feed posts with lazy loading and IntersectionObserver
const FeedImage = memo(function FeedImage({
  src,
  alt,
  index,
}) {
  const imgRef = useRef(null);

  const [shouldLoad, setShouldLoad] = useState(
    index < FAST_IMAGE_LIMIT
  );

useEffect(() => {
  if (shouldLoad || !imgRef.current) {
    return undefined;
  }

  const observer = new IntersectionObserver(
    ([entry]) => {
      if (!entry.isIntersecting) return;

      setShouldLoad(true);
      observer.disconnect();
    },
    {
      rootMargin: IMAGE_PRELOAD_MARGIN,
      threshold: 0,
    }
  );

  observer.observe(imgRef.current);

  return () => observer.disconnect();
}, [shouldLoad]);

  return (
    <img
      ref={imgRef}
      src={shouldLoad ? src : undefined}
      data-src={src}
      alt={alt}
      loading={
        index < FAST_IMAGE_LIMIT ? 'eager' : 'lazy'
      }
      decoding="async"
      fetchPriority={
        index < FAST_IMAGE_LIMIT
          ? 'high'
          : shouldLoad
            ? 'auto'
            : 'low'
      }
      className="feed-image"
    />
  );
});
const FeedPostCard = memo(function FeedPostCard({
  post,
  index,
  creatorName,
  creatorId,
  postId,
  isSaved,
  translatedText,
  isTranslated,
  isTranslating,
  isExplaining,
  explanation,
  onTopicClick,
  onSave,
  onOpenPost,
  onOpenCreator,
  onComments,
  onExplain,
  onTranslateChange,
}) {
  const hasMedia = Boolean(post.videoUrl || post.imageUrl);
  const hasTranslation = Boolean(translatedText);

  return (
    <article
      id={`post-${postId}`}
      className={`snap-post ${!post.imageUrl && !post.videoUrl ? 'no-media' : ''}`}
      onClick={() => onOpenPost(post, creatorName)}
      role="button"
      tabIndex={0}
      onKeyDown={(event) => {
        if (event.key === 'Enter' || event.key === ' ') {
          event.preventDefault();
          onOpenPost(post, creatorName);
        }
      }}
    >
      {hasMedia && (
        <div className="mini-media">
          {post.videoUrl ? (
            <video
              src={post.videoUrl}
              controls
              playsInline
              preload="none"
            />
          ) : (
            <FeedImage
              src={post.imageUrl}
              alt={post.title || 'Post media'}
              index={index}
            />
          )}
        </div>
      )}

      <div className="post-content">
<button
  type="button"
  className="post-topic clickable-topic"
  onClick={(event) => {
    event.stopPropagation();

    onTopicClick(
      getPostTopics(post)[0] || 'Smarty'
    );
  }}
>
  {getPostTopics(post)[0] || 'Smarty'}
</button>

        <div className="post-author">
          {creatorId ? (
            <Link
  to={`/creator/${encodeURIComponent(
    String(creatorId)
  )}`}
  className="creator-link"
  title={`Open ${creatorName}'s creator profile`}
  aria-label={`Open ${creatorName}'s creator profile`}
  onClick={(event) => {
    event.preventDefault();
    event.stopPropagation();
    onOpenCreator(creatorId, postId);
  }}
  state={{
    fromPostId: postId,
    creatorId,
    databaseAuthorId: creatorId,
    databaseAuthor: post.author || '',
    source: 'feed-author-link',
  }}
>
  {creatorName}
</Link>
          ) : (
            <span
              className="creator-link creator-link-disabled"
              title="Creator profile unavailable for this post"
              aria-label="Creator profile unavailable for this post"
            >
              {creatorName}
            </span>
          )}
        </div>

        <h1>{post.title}</h1>
        <p>{isTranslated && translatedText ? translatedText : post.body}</p>

        <div className="post-actions">
          <button
            type="button"
            className={isSaved ? 'icon-action-btn saved' : 'icon-action-btn'}
            disabled={!postId}
            onClick={(event) => {
              event.stopPropagation();
              onSave(postId, isSaved);
            }}
            title={isSaved ? 'Saved' : 'Save'}
            aria-label={isSaved ? 'Saved' : 'Save'}
          >
            <Bookmark size={16} strokeWidth={2.25} fill={isSaved ? 'currentColor' : 'none'} />
          </button>



          <button
            type="button"
            className="icon-action-btn"
            disabled={!postId}
            title="Comments"
            aria-label="Comments"
            onClick={(event) => {
              event.stopPropagation();
              onComments(postId);
            }}
          >
           <MessageCircle size={16} strokeWidth={2.25} />
          </button>

          <button
            type="button"
            className="icon-action-btn"
            title="Simplify"
            aria-label="Simplify"
            onClick={(event) => {
              event.stopPropagation();
              onExplain(post);
            }}
            disabled={isExplaining}
          >
            {isExplaining ? (
             <Loader2 size={16} strokeWidth={2.25} className="spin-icon" />
            ) : (
              <Bot size={16} strokeWidth={2.25} />
            )}
          </button>

          <select
            onClick={(event) => event.stopPropagation()}
            onChange={(event) => onTranslateChange(post, event.target.value)}
            value={isTranslated ? 'translated' : ''}
            className="translate-dropdown"
            disabled={isTranslating}
          >
            <option value="" disabled>
               {isTranslating ? 'Translating...' : 'Translate'}
            </option>
            {hasTranslation && <option value="original">Original</option>}
            {hasTranslation && isTranslated && (
              <option value="translated" disabled>
                Translated
              </option>
            )}
            <option value="Hindi">Hindi</option>
            <option value="Tamil">Tamil</option>
            <option value="Spanish">Spanish</option>
            <option value="French">French</option>
          </select>
        </div>

        {isTranslating && (
          <div className="ai-loading-box">
            <span className="ai-loader-dot"></span>
            <p>Translating...</p>
          </div>
        )}

        {hasTranslation && !isTranslating && !isTranslated && (
          <div className="translated-box">
            <strong>Translation ready</strong>
            <p>Select the translated language again to view it, or choose Original to go back.</p>
          </div>
        )}

        {isExplaining && (
          <div className="ai-loading-box">
            <span className="ai-loader-dot"></span>
            <p>Simplifying...</p>
          </div>
        )}

        {explanation && !isExplaining && (
          <div className="simple-explanation">
            <strong>Simplify</strong>
            <p>{explanation}</p>
          </div>
        )}

        <div className="post-learn-more-hint">
          Click to learn more about this
        </div>
      </div>
    </article>
  );
});

export default function FeedPage() {
  const wrappingTopicCanvasRef = useRef(false);

  const topicRevealFrameRef = useRef(null);
  const topicEdgeLoadLockRef = useRef(false);
  const topicEdgeLoadTimerRef = useRef(null);
  const lastTopicCanvasPositionRef = useRef({
  left: null,
  top: null,
});
const launchTopicsLengthRef = useRef(0);
const topicDisplayLimitRef = useRef(INITIAL_TOPIC_LIMIT);
const topicDragLoadDistanceRef = useRef(0);
const touchGestureRef = useRef({
  startX: 0,
  startY: 0,
  moved: false,
});
const canvasDraggingRef = useRef(false);
const canvasAnimationFrameRef = useRef(null);
const pendingCanvasPositionRef = useRef({
  left: 0,
  top: 0,
});
  const { topic } = useParams();
  const navigate = useNavigate();
  const location = useLocation();
const routeTopic = useMemo(() => {
  const params =
    new URLSearchParams(
      location.search
    );

  return (
    params.get('topic') ||
    topic ||
    ''
  );
}, [location.search, topic]);
  const mountedRef = useRef(true);
  const highlightTimerRef = useRef(null);
  const highlightRemoveTimerRef = useRef(null);
  const requestedCreatorIdsRef = useRef(new Set());
  const toastTimerRef = useRef(null);
  const restoredFeedPositionRef = useRef(false);
const previousTopicCanvasLayoutRef = useRef({
  width: 0,
  height: 0,
  offsetX: 0,
  offsetY: 0,
});
  const {
    posts,
    loading,
    loadingMore,
    error,
    nextCursor,
    loadMore,
    refetch,
    refresh,
    reload,
    savePost,
  } = useFeed();

  const canvasVelocityRef = useRef({
  x: 0,
  y: 0,
});

const canvasMomentumFrameRef = useRef(null);

const lastCanvasMoveTimeRef = useRef(0);

const loadMoreRef = useRef(null);
const feedLoadLockRef = useRef(false);
const topicCanvasRef = useRef(null);
const feedRef = useRef(null);
const wheelAnimationFrameRef = useRef(null);
const topicSearchLoadRef = useRef({
  topic: '',
  cursors: new Set(),
  loading: false,
});

const canvasDragRef = useRef({
  pointerId: null,
  startX: 0,
  startY: 0,
  lastX: 0,
  lastY: 0,
  scrollLeft: 0,
  scrollTop: 0,
  moved: false,
});
const suppressTopicClickRef = useRef(false);
  const [translations, setTranslations] = useState({});
  const [translating, setTranslating] = useState({});
  const [showTranslated, setShowTranslated] = useState({});
  const [selectedTopic, setSelectedTopic] = useState('');
  const [allTopics, setAllTopics] = useState([]);
  const [topicsLoading, setTopicsLoading] = useState(false);
  const [toast, setToast] = useState('');
  const [simpleExplanations, setSimpleExplanations] = useState({});
  const [explaining, setExplaining] = useState({});
  const [savedPostIds, setSavedPostIds] = useState({});
  const [creatorProfiles, setCreatorProfiles] = useState({});
  const [renderLimit, setRenderLimit] = useState(
    INITIAL_RENDER_LIMIT
  );
  const [topicDisplayLimit, setTopicDisplayLimit] = useState(
    INITIAL_TOPIC_LIMIT
  );
  const [isCanvasDragging, setIsCanvasDragging] = useState(false);


const stopCanvasMomentum = useCallback(() => {
  if (canvasMomentumFrameRef.current) {
    cancelAnimationFrame(
      canvasMomentumFrameRef.current
    );

    canvasMomentumFrameRef.current = null;
  }

  canvasVelocityRef.current = {
    x: 0,
    y: 0,
  };
}, []);

const updateTopicCardDepth = useCallback(() => {
  const canvas = topicCanvasRef.current;

  if (!canvas) return;

  const canvasRect =
    canvas.getBoundingClientRect();

  const centerX =
    canvasRect.left +
    canvasRect.width / 2;

  const centerY =
    canvasRect.top +
    canvasRect.height / 2;

  const maxDistance = Math.max(
    1,
    Math.hypot(
      canvasRect.width / 2,
      canvasRect.height / 2
    )
  );

  const cards =
    canvas.querySelectorAll(
      '.topic-launch-card'
    );

  cards.forEach((card) => {
    const cardRect =
      card.getBoundingClientRect();

    const cardCenterX =
      cardRect.left +
      cardRect.width / 2;

    const cardCenterY =
      cardRect.top +
      cardRect.height / 2;

    const distance = Math.hypot(
      cardCenterX - centerX,
      cardCenterY - centerY
    );

    const normalizedDistance =
      Math.min(
        distance / maxDistance,
        1
      );

    const focus =
      1 - normalizedDistance;

    const scale =
      0.76 + focus * 0.24;

    const opacity =
      0.52 + focus * 0.48;

    const lift =
      focus * -8;

    const blur =
      normalizedDistance * 0.35;

    card.style.setProperty(
      '--topic-center-scale',
      scale.toFixed(3)
    );

    card.style.setProperty(
      '--topic-center-opacity',
      opacity.toFixed(3)
    );

    card.style.setProperty(
      '--topic-center-lift',
      `${lift.toFixed(1)}px`
    );

    card.style.setProperty(
      '--topic-center-blur',
      `${blur.toFixed(2)}px`
    );

    card.style.zIndex = String(
      Math.round(focus * 20) + 2
    );
  });
}, []);

const wrapTopicCanvasPosition =
  useCallback(() => {
    const canvas = topicCanvasRef.current;

    if (
      !canvas ||
      wrappingTopicCanvasRef.current
    ) {
      return;
    }

    const maxScrollLeft = Math.max(
      0,
      canvas.scrollWidth -
        canvas.clientWidth
    );

    const maxScrollTop = Math.max(
      0,
      canvas.scrollHeight -
        canvas.clientHeight
    );

    if (
      maxScrollLeft === 0 &&
      maxScrollTop === 0
    ) {
      return;
    }

    const horizontalBuffer = Math.min(
      160,
      Math.max(56, maxScrollLeft * 0.08)
    );

    const verticalBuffer = Math.min(
      160,
      Math.max(56, maxScrollTop * 0.08)
    );

    let nextLeft = canvas.scrollLeft;
    let nextTop = canvas.scrollTop;
    let wrapped = false;

    if (
      maxScrollLeft >
      horizontalBuffer * 2
    ) {
      if (
        canvas.scrollLeft <=
        horizontalBuffer
      ) {
        nextLeft =
          maxScrollLeft -
          horizontalBuffer;

        wrapped = true;
      } else if (
        canvas.scrollLeft >=
        maxScrollLeft -
          horizontalBuffer
      ) {
        nextLeft = horizontalBuffer;
        wrapped = true;
      }
    }

    if (
      maxScrollTop >
      verticalBuffer * 2
    ) {
      if (
        canvas.scrollTop <=
        verticalBuffer
      ) {
        nextTop =
          maxScrollTop -
          verticalBuffer;

        wrapped = true;
      } else if (
        canvas.scrollTop >=
        maxScrollTop -
          verticalBuffer
      ) {
        nextTop = verticalBuffer;
        wrapped = true;
      }
    }

    if (!wrapped) return;

    wrappingTopicCanvasRef.current = true;

    const previousLeft =
      canvas.scrollLeft;

    const previousTop =
      canvas.scrollTop;

    canvas.scrollTo({
      left: nextLeft,
      top: nextTop,
      behavior: 'auto',
    });

    if (canvasDraggingRef.current) {
      canvasDragRef.current.scrollLeft +=
        nextLeft - previousLeft;

      canvasDragRef.current.scrollTop +=
        nextTop - previousTop;
    }

    lastTopicCanvasPositionRef.current = {
      left: nextLeft,
      top: nextTop,
    };

    requestAnimationFrame(() => {
      wrappingTopicCanvasRef.current =
        false;

      updateTopicCardDepth();
    });
  }, [updateTopicCardDepth]);

  
const startCanvasMomentum = useCallback(() => {
  const canvas = topicCanvasRef.current;

  if (!canvas) return;

  stopCanvasMomentum();

  const animateMomentum = () => {
    const currentCanvas =
      topicCanvasRef.current;

    if (!currentCanvas) {
      canvasMomentumFrameRef.current = null;
      return;
    }

    const velocity =
      canvasVelocityRef.current;

    velocity.x *= 0.92;
    velocity.y *= 0.92;

    if (
      Math.abs(velocity.x) < 0.12 &&
      Math.abs(velocity.y) < 0.12
    ) {
      canvasVelocityRef.current = {
        x: 0,
        y: 0,
      };

      canvasMomentumFrameRef.current = null;
      return;
    }

    currentCanvas.scrollLeft -= velocity.x;
    currentCanvas.scrollTop -= velocity.y;

    wrapTopicCanvasPosition();
    updateTopicCardDepth();

    canvasMomentumFrameRef.current =
      requestAnimationFrame(
        animateMomentum
      );
  };

  canvasMomentumFrameRef.current =
    requestAnimationFrame(
      animateMomentum
    );
}, [
  stopCanvasMomentum,
  updateTopicCardDepth,
  wrapTopicCanvasPosition,
]);

const handleCanvasPointerDown = useCallback((event) => {
  if (
    event.pointerType !== 'mouse' ||
    event.button !== 0
  ) {
    return;
  }

  /*
   * Let cards receive normal desktop clicks.
   * Mouse dragging starts only from the canvas background.
   */
if (event.target.closest('.topic-launch-card')) {
  return;
}

  const canvas = topicCanvasRef.current;

  if (!canvas) return;
  stopCanvasMomentum();

lastCanvasMoveTimeRef.current =
  performance.now();

canvasVelocityRef.current = {
  x: 0,
  y: 0,
};
  canvasDraggingRef.current = true;
  suppressTopicClickRef.current = false;
  topicDragLoadDistanceRef.current = 0;

  canvasDragRef.current = {
    pointerId: event.pointerId,
    startX: event.clientX,
    startY: event.clientY,
    lastX: event.clientX,
    lastY: event.clientY,
    scrollLeft: canvas.scrollLeft,
    scrollTop: canvas.scrollTop,
    moved: false,
  };

  canvas.setPointerCapture?.(event.pointerId);
  setIsCanvasDragging(true);
}, [stopCanvasMomentum]);





const handleCanvasPointerMove = useCallback((event) => {
  if (event.pointerType !== 'mouse') {
    return;
  }

  const canvas = topicCanvasRef.current;

  if (
    !canvas ||
    !canvasDraggingRef.current ||
    canvasDragRef.current.pointerId !== event.pointerId
  ) {
    return;
  }

  const deltaX =
    event.clientX - canvasDragRef.current.startX;

  const deltaY =
    event.clientY - canvasDragRef.current.startY;

  const stepX =
    event.clientX - canvasDragRef.current.lastX;

  const stepY =
    event.clientY - canvasDragRef.current.lastY;

  const stepDistance = Math.hypot(stepX, stepY);
  const now = performance.now();

const elapsed = Math.max(
  8,
  now - lastCanvasMoveTimeRef.current
);

lastCanvasMoveTimeRef.current = now;

canvasVelocityRef.current = {
  x: (stepX / elapsed) * 16,
  y: (stepY / elapsed) * 16,
};

  canvasDragRef.current.lastX = event.clientX;
  canvasDragRef.current.lastY = event.clientY;

if (Math.hypot(deltaX, deltaY) > 6) {
  canvasDragRef.current.moved = true;
  suppressTopicClickRef.current = true;
}

const DRAG_SPEED = 0.75;

pendingCanvasPositionRef.current = {
  left:
    canvasDragRef.current.scrollLeft -
    deltaX * DRAG_SPEED,

  top:
    canvasDragRef.current.scrollTop -
    deltaY * DRAG_SPEED,
};

  if (!canvasAnimationFrameRef.current) {
    canvasAnimationFrameRef.current =
      requestAnimationFrame(() => {
        const currentCanvas =
          topicCanvasRef.current;

if (currentCanvas) {
  currentCanvas.scrollLeft =
    pendingCanvasPositionRef.current.left;

  currentCanvas.scrollTop =
    pendingCanvasPositionRef.current.top;

  wrapTopicCanvasPosition();
  updateTopicCardDepth();
}

        canvasAnimationFrameRef.current = null;
      });
  }

  topicDragLoadDistanceRef.current += stepDistance;

  if (
    topicDragLoadDistanceRef.current >= 220 &&
    !topicEdgeLoadLockRef.current &&
    topicDisplayLimitRef.current <
      launchTopicsLengthRef.current
  ) {
    topicDragLoadDistanceRef.current = 0;
    topicEdgeLoadLockRef.current = true;

    setTopicDisplayLimit((current) => {
      const next = Math.min(
        current + TOPIC_BATCH_SIZE,
        launchTopicsLengthRef.current
      );

      topicDisplayLimitRef.current = next;
      return next;
    });

    if (topicEdgeLoadTimerRef.current) {
      clearTimeout(topicEdgeLoadTimerRef.current);
    }

    topicEdgeLoadTimerRef.current =
      window.setTimeout(() => {
        topicEdgeLoadLockRef.current = false;
        topicEdgeLoadTimerRef.current = null;
      }, 180);
  }
}, [
  updateTopicCardDepth,
  wrapTopicCanvasPosition,
]);
const stopCanvasDragging = useCallback((event) => {
  if (event.pointerType !== 'mouse') {
    return;
  }

  const canvas = topicCanvasRef.current;

  canvasDraggingRef.current = false;
  topicDragLoadDistanceRef.current = 0;

  if (canvas?.hasPointerCapture?.(event.pointerId)) {
    canvas.releasePointerCapture(event.pointerId);
  }

  canvasDragRef.current.pointerId = null;

  if (canvasAnimationFrameRef.current) {
    cancelAnimationFrame(
      canvasAnimationFrameRef.current
    );

    canvasAnimationFrameRef.current = null;
  }
if (canvasDragRef.current.moved) {
  startCanvasMomentum();
}
  setIsCanvasDragging(false);

  window.setTimeout(() => {
    suppressTopicClickRef.current = false;
    canvasDragRef.current.moved = false;
  }, 80);
}, [startCanvasMomentum]);

useEffect(() => {
  mountedRef.current = true;

  return () => {
    mountedRef.current = false;

    if (highlightTimerRef.current) {
      clearTimeout(highlightTimerRef.current);
    }

    if (highlightRemoveTimerRef.current) {
      clearTimeout(highlightRemoveTimerRef.current);
    }

    if (topicEdgeLoadTimerRef.current) {
      clearTimeout(topicEdgeLoadTimerRef.current);
      topicEdgeLoadTimerRef.current = null;
    }

    if (topicRevealFrameRef.current) {
      cancelAnimationFrame(topicRevealFrameRef.current);
      topicRevealFrameRef.current = null;
    }

    if (canvasAnimationFrameRef.current) {
      cancelAnimationFrame(canvasAnimationFrameRef.current);
      canvasAnimationFrameRef.current = null;
    }
  };
}, []);

  useEffect(() => {
    const params = new URLSearchParams(location.search);
    const targetPostId = params.get('postId');

    if (!targetPostId) return undefined;

    if (highlightTimerRef.current) clearTimeout(highlightTimerRef.current);
    if (highlightRemoveTimerRef.current) clearTimeout(highlightRemoveTimerRef.current);

    highlightTimerRef.current = window.setTimeout(() => {
      if (!mountedRef.current) return;

      const el = document.getElementById(`post-${targetPostId}`);
      if (el) {
        el.scrollIntoView({ behavior: 'smooth', block: 'center' });
        el.classList.add('highlight-post');

        highlightRemoveTimerRef.current = window.setTimeout(() => {
          el.classList.remove('highlight-post');
        }, 2000);
      }
    }, 450);

    return () => {
      if (highlightTimerRef.current) clearTimeout(highlightTimerRef.current);
      if (highlightRemoveTimerRef.current) clearTimeout(highlightRemoveTimerRef.current);
    };
  }, [location.search, posts.length]);

  const visiblePosts = useMemo(() => {
    const map = new Map();

    (posts || []).forEach((post) => {
      const postId = getPostId(post);
      if (!postId) return;

      const visibility = String(post.visibility || 'public').toLowerCase();

      const canShow =
        visibility === 'public' ||
        visibility === 'published' ||
        visibility === '' ||
        visibility === 'null';

      if (!canShow) return;

      if (!map.has(postId)) {
        map.set(postId, post);
      }
    });

    return Array.from(map.values()).sort((a, b) => getPostTime(b) - getPostTime(a));
  }, [posts]);


  useEffect(() => {
  let cancelled = false;

  async function loadTopics() {
    try {
      setTopicsLoading(true);

      const data = await postApi.getTopics();

      const nextTopics = Array.isArray(data)
        ? data
        : Array.isArray(data?.topics)
          ? data.topics
          : [];

      if (!cancelled && nextTopics.length > 0) {
        setAllTopics(uniqueTopicList(nextTopics));
      }
    } catch (err) {
      console.error('Could not load topics:', err);
    } finally {
      if (!cancelled) setTopicsLoading(false);
    }
  }

  loadTopics();

  return () => {
    cancelled = true;
  };
}, []);


  const handleTranslate = useCallback(async (post, lang = 'Hindi') => {
    const postId = getPostId(post);
    if (!postId || translating[postId]) return;

    try {
      setTranslating((prev) => ({ ...prev, [postId]: true }));

      const data = await postApi.translatePost({
        postId,
        title: post.title,
        body: post.body,
        targetLang: lang,
      });
      if (!mountedRef.current) return;

      const translation = data?.translation?.trim();

      if (!translation || translation === 'Translation not available right now.') {
        setTranslations((prev) => {
          const copy = { ...prev };
          delete copy[postId];
          return copy;
        });

        setShowTranslated((prev) => ({
          ...prev,
          [postId]: false,
        }));

        showToast('Translation failed. Check Lambda logs.');
        return;
      }

      setTranslations((prev) => ({
        ...prev,
        [postId]: translation,
      }));

      setShowTranslated((prev) => ({
        ...prev,
        [postId]: true,
      }));
    } catch (err) {
      console.error('Translate failed:', err);

      setTranslations((prev) => {
        const copy = { ...prev };
        delete copy[postId];
        return copy;
      });

      setShowTranslated((prev) => ({
        ...prev,
        [postId]: false,
      }));

      showToast('Translation failed');
    } finally {
      if (mountedRef.current) {
        setTranslating((prev) => ({ ...prev, [postId]: false }));
      }
    }
  }, [translating]);




const topics = useMemo(() => {
  if (allTopics.length > 0) {
    return ['All', ...allTopics];
  }

  return [
    'All',
    ...uniqueTopicList(
visiblePosts.flatMap((post) => {
  const postTopics =
    getPostTopics(post);

  return postTopics.length > 0
    ? postTopics
    : ['Smarty'];
})
    ),
  ];
}, [allTopics, visiblePosts]);

const launchTopics = useMemo(() => topics, [topics]);

useEffect(() => {
  if (selectedTopic) return;

  const fullTopicCount = launchTopics.length;

  setTopicDisplayLimit(fullTopicCount);
  topicDisplayLimitRef.current = fullTopicCount;
}, [selectedTopic, launchTopics.length]);

const visibleLaunchTopics = useMemo(
  () => launchTopics.slice(0, topicDisplayLimit),
  [launchTopics, topicDisplayLimit]
);

useEffect(() => {
  launchTopicsLengthRef.current =
    launchTopics.length;
}, [launchTopics.length]);

useEffect(() => {
  topicDisplayLimitRef.current =
    topicDisplayLimit;
}, [topicDisplayLimit]);

const topicCanvasLayout = useMemo(
  () =>
    getTopicCanvasLayout(
      visibleLaunchTopics.length
    ),
  [visibleLaunchTopics.length]
);

const topicCanvasSurfaceStyle = useMemo(
  () => ({
    width: `max(${topicCanvasLayout.width}px, calc(100vw + 160px))`,
    height: `max(${topicCanvasLayout.height}px, calc(100% + 160px))`,
  }),
  [
    topicCanvasLayout.height,
    topicCanvasLayout.width,
  ]
);

const filteredPosts = useMemo(() => {
  if (!selectedTopic) return [];

  if (areTopicsEquivalent(selectedTopic, 'All')) {
    return visiblePosts;
  }

  return visiblePosts.filter((post) => {
    const postTopics = getPostTopics(post);

    if (postTopics.length === 0) {
      return areTopicsEquivalent(selectedTopic, 'Smarty');
    }

    return postTopics.some((postTopic) =>
      areTopicsEquivalent(postTopic, selectedTopic)
    );
  });
}, [selectedTopic, visiblePosts]);

useEffect(() => {
  const normalizedSelectedTopic =
    getCanonicalTopic(selectedTopic);

  if (
    !normalizedSelectedTopic ||
    normalizedSelectedTopic === 'all'
  ) {
    topicSearchLoadRef.current = {
      topic: normalizedSelectedTopic,
      cursors: new Set(),
      loading: false,
    };

    return;
  }

  if (
    topicSearchLoadRef.current.topic !==
    normalizedSelectedTopic
  ) {
    topicSearchLoadRef.current = {
      topic: normalizedSelectedTopic,
      cursors: new Set(),
      loading: false,
    };
  }

  if (
    filteredPosts.length > 0 ||
    !nextCursor ||
    loading ||
    loadingMore ||
    topicSearchLoadRef.current.loading
  ) {
    return;
  }

  const cursorKey =
    typeof nextCursor === 'string'
      ? nextCursor
      : JSON.stringify(nextCursor);

  if (
    topicSearchLoadRef.current.cursors.has(cursorKey)
  ) {
    console.warn(
      'Stopped repeated topic cursor:',
      cursorKey
    );

    return;
  }

  topicSearchLoadRef.current.cursors.add(cursorKey);
  topicSearchLoadRef.current.loading = true;

  const requestedTopic = normalizedSelectedTopic;

  Promise.resolve(loadMore())
    .catch((loadError) => {
      console.error(
        'Could not load more posts for topic:',
        selectedTopic,
        loadError
      );
    })
    .finally(() => {
      if (
        topicSearchLoadRef.current.topic ===
        requestedTopic
      ) {
        topicSearchLoadRef.current.loading = false;
      }
    });
}, [
  selectedTopic,
  filteredPosts.length,
  nextCursor,
  loading,
  loadingMore,
  loadMore,
]);

useEffect(() => {
  if (!routeTopic) return;

  let decodedTopic = routeTopic;

  try {
    decodedTopic = decodeURIComponent(routeTopic);
  } catch {
    decodedTopic = routeTopic;
  }

  const matchingTopic = topics.find((item) =>
    areTopicsEquivalent(
      getTopicValue(item),
      decodedTopic
    )
  );

  const nextTopic =
    getTopicValue(matchingTopic) || decodedTopic;

  setSelectedTopic((currentTopic) => {
    if (
      areTopicsEquivalent(currentTopic, nextTopic)
    ) {
      return currentTopic;
    }

    return nextTopic;
  });

  setRenderLimit(INITIAL_RENDER_LIMIT);
}, [routeTopic, topics]);

  const renderedFeedPosts = useMemo(
    () => filteredPosts.slice(0, renderLimit),
    [filteredPosts, renderLimit]
  );

  useEffect(() => {
    const savedPostId = sessionStorage.getItem(FEED_POST_ID_STORAGE_KEY) || '';
    const savedRenderLimit = Number(sessionStorage.getItem(FEED_RENDER_LIMIT_STORAGE_KEY) || 0);

    if (!savedPostId || !filteredPosts.length || restoredFeedPositionRef.current) return;

    const savedPostIndex = filteredPosts.findIndex((post) => getPostId(post) === savedPostId);
    const neededRenderLimit = savedPostIndex >= 0
      ? savedPostIndex + 1
      : savedRenderLimit;

    if (neededRenderLimit > renderLimit) {
      setRenderLimit(Math.min(neededRenderLimit + RENDER_BATCH_SIZE, filteredPosts.length));
    }
  }, [filteredPosts, renderLimit]);




  useEffect(() => {
    if (restoredFeedPositionRef.current) return undefined;

    const savedScrollY = Number(sessionStorage.getItem(FEED_SCROLL_STORAGE_KEY) || 0);
    const savedPostId = sessionStorage.getItem(FEED_POST_ID_STORAGE_KEY) || '';

    if (!savedPostId || !filteredPosts.length || renderedFeedPosts.length === 0) {
      return undefined;
    }

    const savedPostIndex = filteredPosts.findIndex((post) => getPostId(post) === savedPostId);

    if (savedPostIndex >= renderedFeedPosts.length) {
      return undefined;
    }

    const timer = window.setTimeout(() => {
      if (!mountedRef.current) return;

      const savedPostElement = document.getElementById(`post-${savedPostId}`);

      if (!savedPostElement) return;

      restoredFeedPositionRef.current = true;

      savedPostElement.scrollIntoView({
        block: 'start',
        behavior: 'auto',
      });

      requestAnimationFrame(() => {
        requestAnimationFrame(() => {
          if (!mountedRef.current) return;

          if (Number.isFinite(savedScrollY) && savedScrollY > 0 && feedRef.current) {
            feedRef.current.scrollTop = savedScrollY;
            feedRef.current.scrollTo({
              top: savedScrollY,
              behavior: 'auto',
            });
          }
        });
      });
    }, 120);

    return () => clearTimeout(timer);
  }, [filteredPosts, renderedFeedPosts.length]);

  const renderedPostIdSet = useMemo(
    () => new Set(renderedFeedPosts.map((post) => getPostId(post)).filter(Boolean)),
    [renderedFeedPosts]
  );

  useEffect(() => {
    const savedPostId = sessionStorage.getItem(FEED_POST_ID_STORAGE_KEY) || '';

    if (savedPostId && !restoredFeedPositionRef.current) return;

    restoredFeedPositionRef.current = false;
    setRenderLimit(INITIAL_RENDER_LIMIT);
  },  [routeTopic, selectedTopic]);
  const indexOfPostInFeed = useCallback((feedPosts, targetPostId) => (
    feedPosts.findIndex((item) => getPostId(item) === targetPostId)
  ), []);

useEffect(() => {
  if (selectedTopic) return undefined;

  const canvas = topicCanvasRef.current;

  if (!canvas) return undefined;

  const frame = requestAnimationFrame(() => {
    canvas.scrollLeft = Math.max(
      0,
      (canvas.scrollWidth - canvas.clientWidth) / 2
    );

    canvas.scrollTop = Math.max(
      0,
      (canvas.scrollHeight - canvas.clientHeight) / 2
    );

    lastTopicCanvasPositionRef.current = {
      left: canvas.scrollLeft,
      top: canvas.scrollTop,
    };

previousTopicCanvasLayoutRef.current = {
  width: topicCanvasLayout.width,
  height: topicCanvasLayout.height,
  offsetX: topicCanvasLayout.offsetX,
  offsetY: topicCanvasLayout.offsetY,
};
  });

  return () => cancelAnimationFrame(frame);
}, [
  selectedTopic,
  topicCanvasLayout.width,
  topicCanvasLayout.height,
  topicCanvasLayout.offsetX,
  topicCanvasLayout.offsetY,
]);

useEffect(() => {
  const canvas = topicCanvasRef.current;

  if (!canvas || selectedTopic) {
    return undefined;
  }

  const previous =
    previousTopicCanvasLayoutRef.current;

  if (!previous.width || !previous.height) {
    previousTopicCanvasLayoutRef.current = {
      width: topicCanvasLayout.width,
      height: topicCanvasLayout.height,
      offsetX: topicCanvasLayout.offsetX,
      offsetY: topicCanvasLayout.offsetY,
    };

    return undefined;
  }

  const offsetShiftX =
    topicCanvasLayout.offsetX - previous.offsetX;

  const offsetShiftY =
    topicCanvasLayout.offsetY - previous.offsetY;

  previousTopicCanvasLayoutRef.current = {
    width: topicCanvasLayout.width,
    height: topicCanvasLayout.height,
    offsetX: topicCanvasLayout.offsetX,
    offsetY: topicCanvasLayout.offsetY,
  };

  if (offsetShiftX === 0 && offsetShiftY === 0) {
    return undefined;
  }

  const frame = requestAnimationFrame(() => {
    canvas.scrollLeft += offsetShiftX;
    canvas.scrollTop += offsetShiftY;

    lastTopicCanvasPositionRef.current = {
      left: canvas.scrollLeft,
      top: canvas.scrollTop,
    };
  });

  return () => cancelAnimationFrame(frame);
}, [
  selectedTopic,
  topicCanvasLayout.width,
  topicCanvasLayout.height,
  topicCanvasLayout.offsetX,
  topicCanvasLayout.offsetY,
]);

  useEffect(() => {
    const pruneByRenderedPosts = (current) => {
      let changed = false;
      const next = {};

      Object.entries(current).forEach(([postId, value]) => {
        if (renderedPostIdSet.has(postId)) {
          next[postId] = value;
        } else {
          changed = true;
        }
      });

      return changed ? next : current;
    };

    setTranslations(pruneByRenderedPosts);
    setShowTranslated(pruneByRenderedPosts);
    setTranslating(pruneByRenderedPosts);
    setSimpleExplanations(pruneByRenderedPosts);
    setExplaining(pruneByRenderedPosts);
    setSavedPostIds(pruneByRenderedPosts);
  }, [renderedPostIdSet]);

useEffect(() => {
  const target = loadMoreRef.current;
  const root = feedRef.current;

  if (!target || !root || !selectedTopic) {
    return undefined;
  }

  const observer = new IntersectionObserver(
    async ([entry]) => {
      if (
        !entry.isIntersecting ||
        loading ||
        loadingMore ||
        feedLoadLockRef.current
      ) {
        return;
      }

      feedLoadLockRef.current = true;

      try {
        /*
         * First reveal more posts that are already loaded in memory.
         */
        if (renderLimit < filteredPosts.length) {
          setRenderLimit((current) =>
            Math.min(
              current + RENDER_BATCH_SIZE,
              filteredPosts.length
            )
          );

          return;
        }

        /*
         * After all current posts are rendered, request the next API page.
         */
        if (nextCursor) {
          await loadMore();
        }
      } catch (loadError) {
        console.error(
          'Infinite feed load failed:',
          loadError
        );
      } finally {
        window.setTimeout(() => {
          feedLoadLockRef.current = false;
        }, 120);
      }
    },
    {
      root,
      rootMargin: '1200px 0px',
      threshold: 0.01,
    }
  );

  observer.observe(target);

  return () => {
    observer.disconnect();
  };
}, [
  selectedTopic,
  nextCursor,
  loadingMore,
  loading,
  loadMore,
  renderLimit,
  filteredPosts.length,
]);


useEffect(() => {
  if (!loadingMore) {
    feedLoadLockRef.current = false;
  }
}, [loadingMore, nextCursor]);



  const visibleCreatorIds = useMemo(
    () => [
      ...new Set(
        renderedFeedPosts
  .filter((post) => !isSystemGeneratedPost(post))
  .map((post) => getPostCreatorId(post))
  .filter(Boolean)
      ),
    ],
    [renderedFeedPosts]
  );

  useEffect(() => {
    const missingCreatorIds = visibleCreatorIds.filter(
      (id) => !creatorProfiles[id] && !requestedCreatorIdsRef.current.has(id)
    );

    if (missingCreatorIds.length === 0) return undefined;

    let cancelled = false;

    missingCreatorIds.forEach((id) => requestedCreatorIdsRef.current.add(id));

    async function loadCreatorProfiles() {
      const loadedProfiles = {};

      await Promise.allSettled(
        missingCreatorIds.map(async (creatorId) => {
          try {
            const profileResponse = await creatorApi.getProfile(creatorId);
            loadedProfiles[creatorId] = normalizeCreatorProfile(profileResponse);
          } catch (err) {
            requestedCreatorIdsRef.current.delete(creatorId);
            console.error('Could not load creator profile:', creatorId, err);
          }
        })
      );

      if (!cancelled && mountedRef.current && Object.keys(loadedProfiles).length > 0) {
        setCreatorProfiles((prev) => ({ ...prev, ...loadedProfiles }));
      }
    }

    loadCreatorProfiles();

    return () => {
      cancelled = true;
    };
  }, [visibleCreatorIds, creatorProfiles]);

  const showToast = useCallback((message, duration = 1200) => {
    if (toastTimerRef.current) {
      clearTimeout(toastTimerRef.current);
    }

    if (!mountedRef.current) return;

    setToast(message);

    toastTimerRef.current = setTimeout(() => {
      setToast('');
      toastTimerRef.current = null;
    }, duration);
  }, []);

useEffect(() => {
  const canvas = topicCanvasRef.current;

  if (!canvas || selectedTopic) {
    return undefined;
  }

const handleWheel = (event) => {
  event.preventDefault();

  stopCanvasMomentum();

  const WHEEL_SPEED = 0.58;

  const horizontalAmount =
    Math.abs(event.deltaX) >
    Math.abs(event.deltaY)
      ? event.deltaX
      : event.shiftKey
        ? event.deltaY
        : event.deltaX;

  const verticalAmount =
    event.shiftKey
      ? 0
      : event.deltaY;

  canvas.scrollLeft +=
    horizontalAmount *
    WHEEL_SPEED;

  canvas.scrollTop +=
    verticalAmount *
    WHEEL_SPEED;

  if (
    wheelAnimationFrameRef.current
  ) {
    return;
  }

  wheelAnimationFrameRef.current =
    requestAnimationFrame(() => {
      wrapTopicCanvasPosition();
      updateTopicCardDepth();

      wheelAnimationFrameRef.current =
        null;
    });
};



  canvas.addEventListener(
    'wheel',
    handleWheel,
    { passive: false }
  );

return () => {
  canvas.removeEventListener(
    'wheel',
    handleWheel
  );

  if (wheelAnimationFrameRef.current) {
    cancelAnimationFrame(
      wheelAnimationFrameRef.current
    );

    wheelAnimationFrameRef.current = null;
  }
};
}, [
  selectedTopic,
  stopCanvasMomentum,
  updateTopicCardDepth,
  wrapTopicCanvasPosition,
]);

  useEffect(() => {
    return () => {
      if (toastTimerRef.current) {
        clearTimeout(toastTimerRef.current);
        toastTimerRef.current = null;
      }
    };
  }, []);

  const handleSave = useCallback(async (postId, isCurrentlySaved = false) => {
    if (!postId) return;

    try {
      const data = await savePost(postId);
      if (!mountedRef.current) return;

      const nextSavedState = typeof data?.isSaved === 'boolean'
        ? data.isSaved
        : typeof data?.saved === 'boolean'
          ? data.saved
          : !isCurrentlySaved;

      setSavedPostIds((prev) => ({
        ...prev,
        [postId]: nextSavedState,
      }));

      showToast(nextSavedState ? 'Saved successfully 🔖' : 'Removed from saved');
    } catch (err) {
      console.error('Save toggle failed:', err);
      showToast('Bookmark update failed');
    }
  }, [savePost, showToast]);

  const handleExplain = useCallback(async (post) => {
    const postId = getPostId(post);
    if (!postId || explaining[postId]) return;

    if (simpleExplanations[postId]) {
      setSimpleExplanations((prev) => {
        const next = { ...prev };
        delete next[postId];
        return next;
      });
      return;
    }

    const cachedExplanation = getCachedExplanation(post);

    if (cachedExplanation) {
      setSimpleExplanations((prev) => ({
        ...prev,
        [postId]: cachedExplanation,
      }));
      return;
    }

    try {
      setExplaining((prev) => ({ ...prev, [postId]: true }));

      const data = await postApi.explainPost({
        postId,
        title: post.title,
        body: post.body,
      });
      if (!mountedRef.current) return;

      const explanationText =
        data?.explanation ||
        data?.aiExplanation ||
        data?.simpleExplanation ||
        data?.item?.aiExplanation ||
        data?.post?.aiExplanation ||
        'Could not simplify this post.';

      setSimpleExplanations((prev) => ({
        ...prev,
        [postId]: explanationText,
      }));
    } catch (err) {
      console.error('Simplify failed:', err);
      showToast('Could not simplify right now');
    } finally {
      if (mountedRef.current) {
        setExplaining((prev) => ({ ...prev, [postId]: false }));
      }
    }
  }, [explaining, simpleExplanations, showToast]);
  
const selectTopic = useCallback(
  (item, source = 'topic-pill') => {
    const nextTopic =
      getTopicValue(item) || 'All';

    const canonicalNextTopic =
      getCanonicalTopic(nextTopic);

    if (!canonicalNextTopic) {
      showToast('This topic is unavailable');
      return;
    }

    const isCurrentTopic = areTopicsEquivalent(
      selectedTopic,
      nextTopic
    );

    topicSearchLoadRef.current = {
      topic: canonicalNextTopic,
      cursors: new Set(),
      loading: false,
    };

    restoredFeedPositionRef.current = true;

    setSelectedTopic(nextTopic);
    setRenderLimit(INITIAL_RENDER_LIMIT);

    navigate(
      {
        pathname: '/feed',
        search: `?topic=${encodeURIComponent(
          nextTopic
        )}`,
      },
      {
        replace:
          source === 'topic-pill' &&
          isCurrentTopic,
        state: {
          selectedTopic: nextTopic,
          source,
        },
      }
    );

    requestAnimationFrame(() => {
      const feed = feedRef.current;

      if (!feed) return;

      feed.scrollTo({
        top: 0,
        behavior: 'auto',
      });
    });
  },
  [navigate, selectedTopic, showToast]
);

const handleTopicSelect = useCallback(
  (item) => {
    if (
      suppressTopicClickRef.current ||
      canvasDragRef.current.moved ||
      touchGestureRef.current.moved
    ) {
      return;
    }

    selectTopic(item, 'topic-card');
  },
  [selectTopic]
);

const handleTopicPillSelect = useCallback(
  (item) => {
    selectTopic(item, 'topic-pill');
  },
  [selectTopic]
);

const handleTopicClick = useCallback(
  (postTopic) => {
    if (!postTopic) return;

    selectTopic(postTopic, 'post-topic');
  },
  [selectTopic]
);
  // REMOVED handleAiDetails callback block

  const handleComments = useCallback(
    (postId) => {
      if (postId) navigate(`/comments/${postId}`);
    },
    [navigate]
  );

  const handleOpenCreator = useCallback(
  (creatorId, postId = '') => {
    const normalizedCreatorId = String(
      creatorId || ''
    ).trim();

    if (!normalizedCreatorId) {
      showToast('Creator profile unavailable');
      return;
    }

    navigate(
      `/creator/${encodeURIComponent(
        normalizedCreatorId
      )}`,
      {
        state: {
          fromPostId: postId,
          creatorId: normalizedCreatorId,
          databaseAuthorId:
            normalizedCreatorId,
          source: 'feed-author-link',
        },
      }
    );
  },
  [navigate, showToast]
);

  const handleOpenPost = useCallback(
    (post, creatorName) => {
      const postId = getPostId(post);
      if (!postId) return;

      const currentScrollY = feedRef.current?.scrollTop || window.scrollY || 0;
      restoredFeedPositionRef.current = false;
      sessionStorage.setItem(FEED_SCROLL_STORAGE_KEY, String(currentScrollY));
      sessionStorage.setItem(
        FEED_RENDER_LIMIT_STORAGE_KEY,
        String(Math.max(renderLimit, indexOfPostInFeed(filteredPosts, postId) + 1))
      );
      sessionStorage.setItem(FEED_POST_ID_STORAGE_KEY, postId);

      const {
        aiExplanation,
        simpleExplanation,
        explanation,
        explainText,
        simplifiedText,
        ...postForDetails
      } = post;

      navigate(`/post-ai/${postId}`, {
        state: {
          post: {
            ...postForDetails,
            id: postId,
            reelId: postId,
            aiDetailedExplanation: post.aiDetailedExplanation || '',
          },
          creatorName,
          feedScrollY: currentScrollY,
        },
      });
    },
    [filteredPosts, indexOfPostInFeed, navigate, renderLimit]
  );

  const handleTranslateChange = useCallback(
    (post, value) => {
      const postId = getPostId(post);

      if (value === 'original') {
        setShowTranslated((prev) => ({
          ...prev,
          [postId]: false,
        }));
        return;
      }

      handleTranslate(post, value);
    },
    [handleTranslate]
  );

const renderedTopics = useMemo(
  () =>
    launchTopics.map((item) => (
      <TopicPill
        key={getCanonicalTopic(item)}
        item={item}
        active={areTopicsEquivalent(
          selectedTopic,
          item
        )}
        onSelect={handleTopicPillSelect}
      />
    )),
  [
    handleTopicPillSelect,
    selectedTopic,
    launchTopics,
  ]
);

const renderedLaunchTopics = useMemo(
  () =>
    visibleLaunchTopics.map((item, index) => {
      const position =
        getTopicCanvasPosition(index);

      return (
     <TopicLaunchCard
  key={item}
  item={item}
  index={index}
  position={{
    ...position,
    x: position.x + topicCanvasLayout.offsetX,
    y: position.y + topicCanvasLayout.offsetY,
  }}
  onSelect={handleTopicSelect}
/>
      );
    }),
  [
    handleTopicSelect,
    topicCanvasLayout.offsetX,
    topicCanvasLayout.offsetY,
    visibleLaunchTopics,
  ]
);


useEffect(() => {
  if (selectedTopic) return undefined;

  const frame = requestAnimationFrame(() => {
    updateTopicCardDepth();
  });

  return () => {
    cancelAnimationFrame(frame);
  };
}, [
  selectedTopic,
  visibleLaunchTopics.length,
  topicCanvasLayout.width,
  topicCanvasLayout.height,
  updateTopicCardDepth,
]);

const handleTopicCanvasScroll =
  useCallback(() => {
    const canvas =
      topicCanvasRef.current;

    if (!canvas) return;

    if (topicRevealFrameRef.current) {
      cancelAnimationFrame(
        topicRevealFrameRef.current
      );
    }

    topicRevealFrameRef.current =
      requestAnimationFrame(() => {
        wrapTopicCanvasPosition();
        updateTopicCardDepth();

        topicRevealFrameRef.current =
          null;
      });

    if (
      topicEdgeLoadLockRef.current ||
      topicDisplayLimitRef.current >=
        launchTopicsLengthRef.current
    ) {
      return;
    }

    const previous =
      lastTopicCanvasPositionRef.current;

    if (
      previous.left === null ||
      previous.top === null
    ) {
      lastTopicCanvasPositionRef.current = {
        left: canvas.scrollLeft,
        top: canvas.scrollTop,
      };

      return;
    }

    const travelDistance = Math.hypot(
      canvas.scrollLeft -
        previous.left,
      canvas.scrollTop -
        previous.top
    );

    if (travelDistance < 80) return;

    lastTopicCanvasPositionRef.current = {
      left: canvas.scrollLeft,
      top: canvas.scrollTop,
    };

    topicEdgeLoadLockRef.current = true;

    setTopicDisplayLimit((current) => {
      const next = Math.min(
        current + TOPIC_BATCH_SIZE,
        launchTopicsLengthRef.current
      );

      topicDisplayLimitRef.current =
        next;

      return next;
    });

    if (
      topicEdgeLoadTimerRef.current
    ) {
      clearTimeout(
        topicEdgeLoadTimerRef.current
      );
    }

    topicEdgeLoadTimerRef.current =
      window.setTimeout(() => {
        topicEdgeLoadLockRef.current =
          false;

        topicEdgeLoadTimerRef.current =
          null;
      }, 160);
  }, [
    updateTopicCardDepth,
    wrapTopicCanvasPosition,
  ]);


  const renderedPosts = useMemo(
    () => renderedFeedPosts.map((post, index) => {
      const postId = getPostId(post);
     const creatorId = isSystemGeneratedPost(post) ? '' : getPostCreatorId(post);
      const creatorProfile = creatorId ? creatorProfiles[creatorId] : null;
      const creatorName = getDisplayUsername(post, creatorProfile);
      const hasLocalSavedState = Object.prototype.hasOwnProperty.call(savedPostIds, postId);
      const isSaved = hasLocalSavedState
        ? Boolean(savedPostIds[postId])
        : Boolean(
            post.saved ||
              post.isSaved ||
              post.bookmarked ||
              post.isBookmarked ||
              post.savedByCurrentUser
          );

      // const cachedExplanation = getCachedExplanation(post); // Removed unused line
      const visibleExplanation = simpleExplanations[postId] || '';

      return (
<FeedPostCard
  key={`${postId}-${post.createdAtMs || post.updatedAtMs || post.createdAt || post.updatedAt || ''}`}
  post={post}
  index={index}
  postId={postId}
  isSaved={isSaved}
  creatorId={creatorId}
  creatorName={creatorName}
  translatedText={translations[postId]}
  isTranslated={Boolean(showTranslated[postId])}
  isTranslating={Boolean(translating[postId])}
  isExplaining={Boolean(explaining[postId])}
  explanation={visibleExplanation}
  onTopicClick={handleTopicClick}
  onSave={handleSave}
  onOpenPost={handleOpenPost}
  onOpenCreator={handleOpenCreator}
  onComments={handleComments}
  onExplain={handleExplain}
  onTranslateChange={handleTranslateChange}
/>
      );
    }),
    [
      savedPostIds,
      creatorProfiles,
      explaining,
      renderedFeedPosts,
handleOpenPost,
handleOpenCreator,
handleComments,
      handleExplain,
      handleSave,
      handleTopicClick,
      handleTranslateChange,
      showTranslated,
      simpleExplanations,
      translating,
      translations,
    ]
  );

  return (
    <main
      ref={feedRef}
      className="snap-feed-page"
      style={{ overscrollBehaviorY: 'auto' }}
    >


      {toast && <div className="success-toast">{toast}</div>}

{!selectedTopic && (
  <section
    className="topic-launch-screen"
    aria-label="Choose a learning topic"
  >
    <nav className="topic-canvas-navbar" aria-label="Smarty topic navigation">
  <span className="topic-canvas-brand">
    <Sparkles size={15} strokeWidth={2.2} aria-hidden="true" />
    Smarty
  </span>

  <span className="topic-canvas-nav-label">
    Explore topics
  </span>
</nav>

<div className="topic-scroll-hint" aria-hidden="true">
  <span className="topic-scroll-hint-icon">
    <ArrowRight size={14} strokeWidth={2.2} />
  </span>

  <span>Swipe or drag to explore</span>
</div>
    <div
      className="topic-launch-backdrop"
      aria-hidden="true"
    >
      <span className="topic-launch-ambient topic-launch-ambient-one" />
      <span className="topic-launch-ambient topic-launch-ambient-two" />
      <span className="topic-launch-grid-lines" />
    </div>

    <div className="topic-launch-shell">
      <header className="topic-launch-hero">
        <div className="topic-launch-badge">
          <Sparkles
            size={14}
            strokeWidth={2.2}
            aria-hidden="true"
          />

          <span>Choose your feed</span>
        </div>

        {/* <h1>
          What do you want to
          <span> learn?</span>
        </h1> */}

<p>
  Enter a curated learning space tailored to what you want to explore next.
</p>
      </header>

      <div className="topic-launch-content">
        <div className="topic-launch-section-heading">
          <div>
            <span>Topics</span>
            <h2>Choose one to begin</h2>
          </div>
        </div>

        {(loading || topicsLoading) &&
        launchTopics.length === 0 ? (
          <div
            className="topic-launch-loading"
            role="status"
            aria-live="polite"
          >
            <Loader2
              size={20}
              strokeWidth={2.25}
              className="spin-icon"
            />

            <span>Loading topics...</span>
          </div>
        ) : (
          <>
<div
  ref={topicCanvasRef}
  className={`topic-canvas-viewport ${
    isCanvasDragging
      ? 'topic-canvas-dragging'
      : ''
  }`}
  onScroll={handleTopicCanvasScroll}
  onTouchStart={(event) => {
    const canvas = topicCanvasRef.current;
    const touch = event.touches?.[0];

    if (!canvas || !touch) return;

    touchGestureRef.current = {
      startX: touch.clientX,
      startY: touch.clientY,
      moved: false,
    };

    canvasDragRef.current.moved = false;

    lastTopicCanvasPositionRef.current = {
      left: canvas.scrollLeft,
      top: canvas.scrollTop,
    };
  }}
  onTouchMove={(event) => {
    const touch = event.touches?.[0];

    if (!touch) return;

    const deltaX =
      touch.clientX -
      touchGestureRef.current.startX;

    const deltaY =
      touch.clientY -
      touchGestureRef.current.startY;

    if (Math.hypot(deltaX, deltaY) > 8) {
      touchGestureRef.current.moved = true;
      canvasDragRef.current.moved = true;
    }
  }}
  onTouchEnd={() => {
    window.setTimeout(() => {
      touchGestureRef.current.moved = false;
      canvasDragRef.current.moved = false;
    }, 80);
  }}
onPointerDown={handleCanvasPointerDown}
onPointerMove={handleCanvasPointerMove}
onPointerUp={stopCanvasDragging}
onPointerCancel={stopCanvasDragging}
onLostPointerCapture={(event) => {
  if (event.pointerType === 'mouse') {
    canvasDraggingRef.current = false;
    canvasDragRef.current.pointerId = null;
    canvasDragRef.current.moved = false;
suppressTopicClickRef.current = false;
    setIsCanvasDragging(false);
  }
}}
>
<div
  className="topic-canvas-surface"
style={topicCanvasSurfaceStyle}
>
  {renderedLaunchTopics}
</div>
</div>


          </>
        )}
      </div>
    </div>
  </section>
)}

      {selectedTopic && (
        <section className="topic-rail mobile-feed-topic-rail" aria-label="Feed topics">


          <div className="mobile-topic-scroll" role="tablist" aria-label="Select feed topic">
            {renderedTopics}
          </div>
        </section>
      )}

{selectedTopic && loading && filteredPosts.length === 0 && (
  <FeedSkeleton />
)}

{selectedTopic && error && (
  <div
    className="feed-status error"
    role="alert"
  >
    <p>{error}</p>

    <button
      type="button"
      onClick={() => {
        const retry =
          refetch || refresh || reload;

        if (typeof retry === 'function') {
          retry();
        }
      }}
    >
      Try again
    </button>
  </div>
)}

{selectedTopic &&
  !loading &&
  !loadingMore &&
  !error &&
  filteredPosts.length === 0 &&
  !nextCursor && (
    <p className="feed-status">
      No posts found in this topic.
    </p>
  )}

{selectedTopic &&
  !loading &&
  !error &&
  filteredPosts.length === 0 &&
  nextCursor && (
    <p className="feed-status">
      Loading topic posts...
    </p>
  )}

{selectedTopic && (
  <section className="snap-feed">
    {renderedPosts}

    <div
      ref={loadMoreRef}
      className="feed-load-trigger"
      aria-hidden="true"
    />
  </section>
)}

{selectedTopic &&
  (loadingMore ||
    renderLimit < filteredPosts.length) && (
    <p className="feed-status">
      Loading more posts...
    </p>
  )}
    </main>
  );
}

function getTopicCanvasPosition(index) {
  const cardsPerCluster = 12;

  

  const clusterCards = [
    { x: 16, y: 26, width: 210, height: 150 },
    { x: 254, y: 26, width: 180, height: 190 },
    { x: 462, y: 26, width: 228, height: 150 },

    { x: 16, y: 244, width: 184, height: 188 },
    { x: 228, y: 244, width: 244, height: 150 },
    { x: 500, y: 244, width: 190, height: 190 },

    { x: 16, y: 462, width: 226, height: 152 },
    { x: 270, y: 462, width: 182, height: 190 },
    { x: 480, y: 462, width: 218, height: 150 },

    { x: 16, y: 680, width: 188, height: 180 },
    { x: 232, y: 680, width: 232, height: 148 },
    { x: 492, y: 680, width: 176, height: 184 },
  ];

const clusterIndex = Math.floor(
  index / cardsPerCluster
);

const cardIndex = index % cardsPerCluster;
const cluster = getSpiralClusterPosition(clusterIndex);
const card = clusterCards[cardIndex];

const isDesktop =
  typeof window !== 'undefined' &&
  window.innerWidth >= 1024;

const clusterWidth = isDesktop ? 860 : 740;
const clusterHeight = isDesktop ? 1080 : 920;

const canvasCenterX = 1050;
const canvasCenterY = 720;

return {
  width: card.width,
  height: card.height,
  x:
    canvasCenterX +
    cluster.x * clusterWidth +
    card.x,
  y:
    canvasCenterY +
    cluster.y * clusterHeight +
    card.y,
};
}

function getSpiralClusterPosition(index) {
  if (index === 0) {
    return { x: 0, y: 0 };
  }

  const spiral = [
    { x: 1, y: 0 },
    { x: 1, y: 1 },
    { x: 0, y: 1 },
    { x: -1, y: 1 },
    { x: -1, y: 0 },
    { x: -1, y: -1 },
    { x: 0, y: -1 },
    { x: 1, y: -1 },

    { x: 2, y: -1 },
    { x: 2, y: 0 },
    { x: 2, y: 1 },
    { x: 2, y: 2 },
    { x: 1, y: 2 },
    { x: 0, y: 2 },
    { x: -1, y: 2 },
    { x: -2, y: 2 },
    { x: -2, y: 1 },
    { x: -2, y: 0 },
    { x: -2, y: -1 },
    { x: -2, y: -2 },
    { x: -1, y: -2 },
    { x: 0, y: -2 },
    { x: 1, y: -2 },
    { x: 2, y: -2 },
  ];

  return (
    spiral[index - 1] || {
      x: index % 5,
      y: Math.floor(index / 5),
    }
  );
}



function getTopicCanvasLayout(topicCount) {
  const edgePadding = 20;

  const cards = Array.from(
    { length: topicCount },
    (_, index) => ({
      index,
      ...getTopicCanvasPosition(index),
    })
  );

  if (cards.length === 0) {
    return {
      width: 800,
      height: 700,
      offsetX: 0,
      offsetY: 0,
    };
  }

  const minX = Math.min(
    ...cards.map((card) => card.x)
  );

  const minY = Math.min(
    ...cards.map((card) => card.y)
  );

  const maxX = Math.max(
    ...cards.map(
      (card) => card.x + card.width
    )
  );

  const maxY = Math.max(
    ...cards.map(
      (card) => card.y + card.height
    )
  );

  return {
    width:
      maxX -
      minX +
      edgePadding * 2,

    height:
      maxY -
      minY +
      edgePadding * 2,

    offsetX:
      edgePadding - minX,

    offsetY:
      edgePadding - minY,
  };
}