"""Curated, concrete learning targets for Smarty's generated feed.

The parent key is the topic shown in the UI. Every value is deliberately narrower
than that parent so generation begins with a teachable mechanism, event, component,
experiment, or case rather than a broad summary.
"""

TOPIC_SUBTOPICS = {
    "Artificial Intelligence": (
        "how self-attention heads connect tokens across a prompt",
        "how a KV cache avoids recomputing earlier tokens",
        "how byte-pair encoding turns text into model tokens",
        "how LoRA adapters update a model with low-rank matrices",
        "how mixture-of-experts routing selects a small set of experts",
        "how retrieval-augmented generation chooses supporting passages",
        "how quantization compresses model weights into fewer bits",
        "how diffusion models learn to reverse a noise process",
        "how preference models turn human rankings into a training signal",
        "how prompt injection crosses the boundary between data and instructions",
    ),
    "Machine Learning": (
        "why gradient descent follows the slope of a loss surface",
        "how backpropagation assigns error to individual weights",
        "how decision trees choose a feature split",
        "why regularization can improve performance on unseen data",
        "how cross-validation exposes an overfit model",
        "how class imbalance distorts an accuracy score",
    ),
    "Data Science": (
        "how Simpson's paradox reverses a trend after groups are combined",
        "why data leakage makes a weak model look accurate",
        "how missing-value mechanisms change the right imputation method",
        "how feature scaling changes distance-based models",
        "how a confusion matrix separates different kinds of error",
    ),
    "Robotics": (
        "how an encoder closes the feedback loop on a robot joint",
        "how inverse kinematics chooses joint angles for a target position",
        "how a lidar scan becomes a map through SLAM",
        "why compliant grippers can hold irregular objects",
        "how a Kalman filter combines noisy robot sensors",
    ),
    "Cybersecurity": (
        "how a buffer overflow can overwrite a return address",
        "how passkeys replace shared passwords with public-key proofs",
        "how DNS cache poisoning redirects a trusted domain",
        "how a zero-day moves from discovery to responsible disclosure",
        "how rate limiting slows credential-stuffing attacks",
    ),
    "Cryptography": (
        "how Diffie-Hellman creates a shared secret over a public channel",
        "why password hashing uses salt and deliberately expensive work",
        "how digital signatures reveal message tampering",
        "how authenticated encryption detects modified ciphertext",
        "how Merkle trees verify one record without downloading every record",
    ),
    "Software Systems": (
        "how idempotency keys prevent duplicate payments",
        "how a circuit breaker stops one failure from cascading",
        "why distributed clocks cannot perfectly order every event",
        "how write-ahead logs recover interrupted database changes",
        "how backpressure keeps a fast producer from overwhelming a consumer",
    ),
    "Databases": (
        "how B-trees keep database indexes shallow",
        "how MVCC lets readers and writers avoid blocking each other",
        "why a composite index depends on column order",
        "how a database executes a join without comparing every row",
        "how quorum reads trade consistency for availability",
    ),
    "Operating Systems": (
        "how virtual memory turns page faults into disk reads",
        "how a scheduler shares one CPU core among many processes",
        "why copy-on-write makes process creation cheaper",
        "how a system call crosses from user mode into the kernel",
        "how deadlock forms from a cycle of held resources",
    ),
    "Computer Networks": (
        "how TCP congestion control reacts to packet loss",
        "how a router chooses the next hop for an IP packet",
        "how DNS resolution walks from root servers to an authoritative answer",
        "why TLS uses both asymmetric and symmetric cryptography",
        "how content delivery networks move files closer to readers",
    ),
    "Cloud Computing": (
        "how an autoscaler decides when to add capacity",
        "how object storage achieves durability with redundant copies",
        "why serverless cold starts happen and what work occurs inside one",
        "how availability zones limit the blast radius of failure",
        "how eventual consistency appears after a distributed write",
    ),
    "Semiconductors": (
        "how a MOSFET gate controls current without touching the channel",
        "why photolithography repeats many masks on a silicon wafer",
        "how chiplets exchange data across a package",
        "why transistor leakage rises as features shrink",
        "how error-correcting memory detects and repairs a flipped bit",
    ),
    "Electronics": (
        "how a buck converter lowers voltage by rapid switching",
        "how a capacitor smooths ripple after rectification",
        "why an operational amplifier uses negative feedback",
        "how a phase-locked loop follows an incoming frequency",
        "how a transistor turns a small signal into a larger one",
    ),
    "Engineering": (
        "how a truss redirects a load into tension and compression",
        "why fatigue cracks grow under repeated small loads",
        "how a governor holds a machine near a target speed",
        "how finite-element meshes approximate stress inside a part",
        "why engineering safety factors differ by failure mode",
    ),
    "Manufacturing": (
        "how injection molding fills and cools a complex cavity",
        "how CNC toolpaths turn a digital model into a metal part",
        "why tolerance stack-up can stop an assembly from fitting",
        "how a poka-yoke fixture prevents the wrong assembly step",
        "how additive manufacturing supports are removed after printing",
    ),
    "Materials Science": (
        "how heat treatment changes the grain structure of steel",
        "why carbon-fiber direction controls composite strength",
        "how dislocations let a metal bend without breaking",
        "how shape-memory alloys return to a trained form",
        "why tempered glass breaks into small blunt pieces",
    ),
    "Aviation": (
        "how a turbofan divides thrust between its core and bypass air",
        "how wingtip vortices create induced drag",
        "why aircraft cabins are pressurized below sea-level pressure",
        "how a pitot-static system measures airspeed and altitude",
        "how fly-by-wire software keeps an unstable aircraft controllable",
    ),
    "Transportation": (
        "how regenerative braking returns motion to a battery",
        "why a differential lets two wheels turn at different speeds",
        "how railway signaling keeps trains out of occupied blocks",
        "how a catalytic converter changes harmful exhaust gases",
        "why traffic shockwaves move backward along a highway",
    ),
    "Energy": (
        "how a grid inverter synchronizes solar power with the mains",
        "why pumped-storage plants act like giant batteries",
        "how a heat pump moves more heat than its electrical input",
        "how uranium fission becomes controlled reactor heat",
        "why long-distance transmission uses very high voltage",
    ),
    "Infrastructure": (
        "how expansion joints let a bridge survive temperature changes",
        "how a water tower stabilizes pressure during demand spikes",
        "why storm drains can overflow without any broken pipe",
        "how base isolation reduces earthquake force on a building",
        "how a tunnel-boring machine supports fresh ground as it advances",
    ),
    "Architecture": (
        "how a passive house controls heat through its envelope",
        "how a flying buttress moves roof thrust away from a wall",
        "why daylight shelves send light deeper into a room",
        "how stack ventilation moves air without a fan",
        "how adaptive reuse preserves a structure while changing its purpose",
    ),
    "Physics": (
        "how angular momentum keeps a spinning gyroscope upright",
        "why resonance can amplify a tiny repeated force",
        "how a photon ejects an electron in the photoelectric effect",
        "how entropy counts the number of hidden microscopic arrangements",
        "why superconductors expel magnetic fields below a critical temperature",
    ),
    "Chemistry": (
        "how a catalyst lowers the activation-energy barrier",
        "why buffer solutions resist a change in pH",
        "how chirality makes two mirror-image molecules behave differently",
        "how chromatography separates molecules by competing attractions",
        "why rust needs both oxygen and an electrolyte",
    ),
    "Biology": (
        "how ATP synthase turns a proton gradient into chemical energy",
        "how ribosomes translate messenger RNA into a protein",
        "why cell membranes self-assemble into a bilayer",
        "how apoptosis dismantles a damaged cell without inflammation",
        "how quorum sensing lets bacteria measure crowd density",
    ),
    "Genetics": (
        "how crossing-over reshuffles genes during meiosis",
        "how CRISPR-Cas9 locates and cuts a matching DNA sequence",
        "why one gene can produce several proteins through alternative splicing",
        "how epigenetic tags change gene activity without rewriting DNA",
        "how genetic drift can fix a neutral trait in a small population",
    ),
    "Neuroscience": (
        "how myelin makes an electrical signal jump between nodes",
        "how synaptic pruning reshapes a developing brain",
        "how dopamine prediction errors update an expected reward",
        "how the hippocampus binds separate details into one memory",
        "how lateral inhibition sharpens the edge of a visual signal",
    ),
    "Human Body": (
        "how the kidney loop of Henle concentrates urine",
        "how hemoglobin changes its grip on oxygen in active tissue",
        "how the inner ear converts fluid movement into balance signals",
        "how the pancreas coordinates insulin and glucagon",
        "how tendons store and return elastic energy while running",
    ),
    "Immunology": (
        "how antibodies neutralize a virus without killing it directly",
        "how T cells distinguish infected cells from healthy cells",
        "why a second vaccine dose strengthens immune memory",
        "how complement proteins punch holes in bacterial membranes",
        "how allergies misclassify a harmless substance as a threat",
    ),
    "Microbiology": (
        "how bacteriophages inject DNA through a bacterial wall",
        "how biofilms protect microbes inside a sticky matrix",
        "why antibiotics can spare resistant bacteria to multiply",
        "how yeast switches sugar into carbon dioxide and ethanol",
        "how endospores preserve a bacterium through extreme conditions",
    ),
    "Astronomy": (
        "how transit timing reveals an unseen exoplanet",
        "how stellar parallax turns an angle into a distance",
        "why pulsars behave like precise cosmic clocks",
        "how spectroscopy identifies elements inside a distant star",
        "how gravitational lensing magnifies a galaxy behind a cluster",
    ),
    "Space": (
        "how orbital resonance repeatedly tugs neighboring moons",
        "how a gravity assist exchanges momentum with a planet",
        "why a spacecraft uses a Lagrange point instead of orbiting Earth",
        "how reaction wheels rotate a satellite without firing a thruster",
        "how ablative heat shields carry reentry heat away",
    ),
    "Earth Science": (
        "how seismic waves reveal layers inside Earth",
        "how mantle convection moves tectonic plates",
        "why Earth's magnetic poles occasionally reverse",
        "how isostatic rebound lifts land after an ice sheet melts",
        "how radiometric dating turns isotope ratios into rock ages",
    ),
    "Geology": (
        "how a subduction zone recycles oceanic crust",
        "why columnar basalt forms hexagonal cracks",
        "how groundwater carves a limestone cave",
        "how graded bedding records the direction of an ancient flow",
        "why liquefaction makes firm ground behave like a fluid",
    ),
    "Oceanography": (
        "how thermohaline circulation links distant ocean basins",
        "why coastal upwelling creates rich fishing grounds",
        "how internal waves travel along layers beneath the surface",
        "how coral polyps build reefs from calcium carbonate",
        "why rogue waves can grow much taller than neighboring waves",
    ),
    "Weather": (
        "how a supercell's rotating updraft can produce a tornado",
        "why freezing rain stays liquid until it hits the ground",
        "how a temperature inversion traps pollution near a city",
        "how jet-stream bends steer surface weather systems",
        "why lake-effect snow forms in narrow downwind bands",
    ),
    "Climate Change": (
        "how ice-albedo feedback amplifies Arctic warming",
        "how ocean acidification changes carbonate available to shell builders",
        "why thawing permafrost can release additional greenhouse gases",
        "how tree rings preserve a record of past rainfall",
        "how urban heat islands raise nighttime temperatures",
    ),
    "Ecology": (
        "how a keystone predator reshapes an entire food web",
        "how mycorrhizal fungi trade minerals with plant roots",
        "why island populations are especially vulnerable to invasive species",
        "how ecological succession rebuilds a disturbed landscape",
        "how nitrogen fixation makes atmospheric nitrogen usable by plants",
    ),
    "Environment": (
        "how a constructed wetland removes nutrients from wastewater",
        "why microplastics accumulate through aquatic food chains",
        "how groundwater pumping can make land slowly sink",
        "how riparian buffers keep farm runoff out of rivers",
        "how a landfill captures methane from decomposing waste",
    ),
    "Mathematics": (
        "why prime-number factorization makes some cryptography practical",
        "how Fourier transforms rebuild a signal from frequencies",
        "how a fixed point emerges from repeated application of a function",
        "why non-Euclidean geometry changes the angles of a triangle",
        "how eigenvectors reveal directions a transformation does not rotate",
    ),
    "Statistics": (
        "why regression to the mean follows an extreme measurement",
        "how a confidence interval differs from a probability about one parameter",
        "why optional stopping inflates false-positive results",
        "how Bayesian updating combines prior belief with new evidence",
        "how survivorship bias removes failures from the visible sample",
    ),
    "Probability": (
        "why the birthday paradox reaches fifty percent so quickly",
        "how conditional probability changes after new evidence",
        "why independent events can still produce long streaks",
        "how the law of large numbers stabilizes an average",
        "how the Monty Hall problem reveals information in a host's choice",
    ),
    "Psychology": (
        "how cognitive dissonance changes a belief after a difficult choice",
        "why the spacing effect strengthens long-term recall",
        "how variable rewards make a behavior persist",
        "why inattentional blindness hides an obvious event",
        "how the peak-end rule compresses an experience into two moments",
    ),
    "Human Behavior": (
        "how social proof grows stronger under uncertainty",
        "why people copy effort when responsibility is shared",
        "how loss aversion changes the price someone will accept",
        "why default choices influence behavior without removing options",
        "how reciprocity creates pressure to return a favor",
    ),
    "Decision Making": (
        "how base-rate neglect distorts a medical-test result",
        "why sunk costs keep a failing project alive",
        "how choice architecture changes a decision without changing facts",
        "why pre-mortems reveal risks that optimism hides",
        "how expected value separates outcome size from outcome probability",
    ),
    "Memory": (
        "how reconsolidation can alter a memory after it is recalled",
        "why retrieval practice beats rereading for durable recall",
        "how interference makes similar memories compete",
        "how chunking expands the practical limit of working memory",
        "why context cues can unlock a memory that seemed lost",
    ),
    "Learning": (
        "how interleaving teaches the brain to choose between methods",
        "why desirable difficulty improves later recall",
        "how worked examples reduce cognitive load for beginners",
        "why immediate feedback can prevent an error from becoming a habit",
        "how transfer fails when knowledge stays tied to one context",
    ),
    "Sleep": (
        "how adenosine builds sleep pressure across the day",
        "how the suprachiasmatic nucleus resets the circadian clock",
        "why REM sleep temporarily paralyzes most skeletal muscles",
        "how slow-wave sleep supports memory consolidation",
        "why late caffeine can remain active at bedtime",
    ),
    "Nutrition": (
        "how soluble fiber slows glucose absorption in the intestine",
        "why protein triggers a larger thermic effect than fat",
        "how bile salts break dietary fat into absorbable droplets",
        "how resistant starch reaches and feeds colon bacteria",
        "why iron absorption changes with the chemical form of a meal",
    ),
    "Fitness": (
        "how progressive overload signals a muscle to adapt",
        "why tendons strengthen more slowly than muscles",
        "how the stretch-shortening cycle powers a jump",
        "how lactate is reused as fuel instead of remaining a waste product",
        "why aerobic training increases mitochondrial density",
    ),
    "Health": (
        "how insulin moves glucose transporters to a cell surface",
        "why blood pressure changes when arteries lose elasticity",
        "how fever changes the body's temperature set point",
        "how wound healing moves through clotting, inflammation, and remodeling",
        "why dehydration raises heart rate during exercise",
    ),
    "Mental Health": (
        "how exposure therapy updates a learned fear prediction",
        "why rumination keeps a stress response active after an event",
        "how slow breathing influences the autonomic nervous system",
        "how behavioral activation interrupts the withdrawal cycle",
        "why sleep disruption can amplify emotional reactivity",
    ),
    "Finance": (
        "how duration predicts a bond's response to interest-rate changes",
        "how a bank creates a loan while managing reserve and capital limits",
        "why inflation transfers purchasing power between borrowers and lenders",
        "how compound interest changes when contributions arrive monthly",
        "how a yield curve embeds expectations about future rates",
    ),
    "Investing": (
        "how index rebalancing creates predictable trades",
        "why diversification depends on correlation rather than asset count",
        "how dividend reinvestment changes long-run share ownership",
        "how sequence-of-returns risk affects retirement withdrawals",
        "why a valuation multiple can rise while earnings fall",
    ),
    "Personal Finance": (
        "how credit-card grace periods change the cost of a purchase",
        "why an emergency fund reduces forced selling",
        "how tax brackets apply different rates to slices of income",
        "how mortgage amortization shifts from interest toward principal",
        "why expense ratios compound into large differences over decades",
    ),
    "Stock Market": (
        "how an order book matches market orders with limit orders",
        "why a short squeeze forces buying as a price rises",
        "how a stock split changes share count without changing company value",
        "how circuit breakers interrupt a rapidly falling market",
        "why bid-ask spreads widen when liquidity disappears",
    ),
    "Economics": (
        "how comparative advantage creates gains even for a stronger producer",
        "why price ceilings can create shortages",
        "how a central bank rate reaches household borrowing costs",
        "how network effects can tip a market toward one platform",
        "why a negative externality produces too much of an activity",
    ),
    "Global Economy": (
        "how dollar-denominated debt tightens when the dollar rises",
        "why container shortages can raise prices far from a port",
        "how currency pegs are defended with foreign reserves",
        "how a sovereign-debt rollover can become a crisis",
        "why commodity shocks affect importing and exporting countries differently",
    ),
    "Business": (
        "how working capital can consume cash during rapid growth",
        "why contribution margin matters before total profit",
        "how queue design changes service capacity and wait time",
        "how switching costs protect a product from competitors",
        "why a bottleneck sets the output of an entire operation",
    ),
    "Startups": (
        "how cohort retention reveals product-market fit",
        "why dilution changes a founder's ownership after each funding round",
        "how a marketplace solves the cold-start problem",
        "why runway depends on net burn rather than expenses alone",
        "how a wedge product opens a larger market",
    ),
    "Marketing": (
        "how incrementality tests separate real lift from ordinary purchases",
        "why message-market fit changes conversion more than button color",
        "how frequency capping prevents advertising fatigue",
        "how attribution windows assign one sale to competing channels",
        "why distinctive brand assets improve recognition before recall",
    ),
    "Consumer Behavior": (
        "how decoy pricing changes the comparison between two products",
        "why scarcity cues lose power when they appear artificial",
        "how shelf position affects what shoppers notice first",
        "why ownership raises the price people demand to give something up",
        "how choice overload can shift a customer toward the default",
    ),
    "Supply Chain": (
        "how the bullwhip effect amplifies a small change in demand",
        "why safety stock rises with both uncertainty and lead time",
        "how cross-docking moves goods without storing them",
        "how cold-chain breaks shorten the remaining life of food",
        "why a single-source component can stop an entire assembly line",
    ),
    "Agriculture": (
        "how crop rotation interrupts pests while restoring soil nutrients",
        "why drip irrigation reduces evaporation near plant roots",
        "how grafting combines one plant's roots with another plant's fruit",
        "how no-till farming changes soil structure and water retention",
        "why pollination timing limits the yield of some crops",
    ),
    "Food Science": (
        "how the Maillard reaction creates roasted flavors",
        "why an emulsion keeps oil suspended in water",
        "how gluten traps gas inside rising bread dough",
        "why flash freezing makes smaller ice crystals",
        "how fermentation acidity changes food safety and flavor",
    ),
    "History": (
        "how Roman concrete survived repeated contact with seawater",
        "why the printing press changed the speed of religious conflict",
        "how the Black Death altered bargaining power for laborers",
        "how standardized time grew from railway scheduling",
        "why the telegraph separated communication speed from travel speed",
    ),
    "Ancient Civilizations": (
        "how Mesopotamian cuneiform grew from accounting tokens",
        "how Nile flood measurements shaped Egyptian taxation",
        "why Roman roads were layered for drainage and repair",
        "how Maya cities stored water through long dry seasons",
        "how Indus cities organized drainage without known royal monuments",
    ),
    "World History": (
        "how the Columbian Exchange moved crops, disease, and labor systems",
        "why the Suez Canal redirected trade between Europe and Asia",
        "how smallpox vaccination traveled through chained human carriers",
        "how the silver trade connected mines in the Americas to markets in China",
        "why decolonization produced very different political borders",
    ),
    "Geopolitical History": (
        "how the Sykes-Picot map shaped competing postwar claims",
        "why the Berlin Conference accelerated partition in Africa",
        "how the India-Pakistan partition turned a border into mass migration",
        "how Cold War alliances placed distant conflicts inside a global rivalry",
        "why access to warm-water ports repeatedly shaped Russian strategy",
    ),
    "Military History": (
        "how the stirrup changed the stability of mounted combat",
        "why trench systems turned movement into attrition",
        "how radar altered the Battle of Britain",
        "how logistics limited Napoleon's advance into Russia",
        "why aircraft carriers replaced battleships as the center of naval power",
    ),
    "Political History": (
        "how the secret ballot changed the power of local patrons",
        "why census design became a struggle over representation",
        "how parliamentary confidence votes constrain a government",
        "how civil-service exams weakened inherited administrative power",
        "why emergency powers often outlast the crisis that created them",
    ),
    "Economic History": (
        "how double-entry bookkeeping changed the scale of merchant firms",
        "why the gold standard transmitted one country's shock to another",
        "how containerization reduced the cost of loading a ship",
        "how joint-stock companies spread the risk of long voyages",
        "why the assembly line changed both wages and product prices",
    ),
    "Diplomatic History": (
        "how the Congress of Vienna used a balance of power to contain conflict",
        "why the hotline changed crisis communication after the Cuban Missile Crisis",
        "how diplomatic recognition can exist without a formal alliance",
        "how the Treaty of Tordesillas divided claims before maps were accurate",
        "why back-channel negotiation can unlock a public stalemate",
    ),
    "Colonial History": (
        "how chartered companies governed territory for private profit",
        "why cash-crop taxes pushed households into colonial labor markets",
        "how railway routes served extraction before local mobility",
        "how indirect rule changed existing systems of authority",
        "why colonial language policy still shapes education systems",
    ),
    "Borders and Empires": (
        "how the Roman limes worked as a managed frontier rather than a single wall",
        "why straight-line borders can hide older movement routes",
        "how buffer states separated rival empires",
        "how river movement turns a natural border into a legal dispute",
        "why imperial collapse creates overlapping territorial claims",
    ),
    "Medieval History": (
        "how a castle's concentric walls created overlapping defenses",
        "why monastic scriptoria preserved and changed copied texts",
        "how the Hanseatic League protected merchants without becoming a state",
        "how crop rotation supported the growth of medieval towns",
        "why pilgrimage routes became channels for trade and disease",
    ),
    "Modern History": (
        "how radio turned political speeches into simultaneous mass events",
        "why passport controls became normal during the First World War",
        "how household refrigeration reorganized food supply chains",
        "how satellite television crossed borders that censored print",
        "why the shipping container remade port cities",
    ),
    "Trade Routes": (
        "how monsoon winds scheduled trade across the Indian Ocean",
        "why caravanserais reduced risk along Silk Road segments",
        "how the Strait of Malacca became a strategic trade chokepoint",
        "how trans-Saharan salt and gold moved in opposite directions",
        "why relay stations increased the speed of overland messages",
    ),
    "Revolutions": (
        "how bread prices became a political trigger in the French Revolution",
        "why printing networks helped revolutionary ideas outrun authorities",
        "how competing armies shaped the course of the Haitian Revolution",
        "how land reform divided allies after successful revolutions",
        "why military defections can decide whether a regime survives protests",
    ),
    "Archaeology": (
        "how stratigraphy turns soil layers into a relative timeline",
        "how pollen grains reveal plants around an ancient settlement",
        "why pottery fragments can map trade without written records",
        "how lidar finds earthworks beneath a forest canopy",
        "how isotope ratios trace where an ancient person grew up",
    ),
    "Anthropology": (
        "how kinship terms encode social obligations",
        "why gift exchange can create durable political relationships",
        "how participant observation reveals rules people rarely state",
        "how food taboos adapt to ecology and identity",
        "why rites of passage separate, transform, and reintegrate participants",
    ),
    "Sociology": (
        "how weak social ties spread opportunities between groups",
        "why broken-window measurements can confuse cause and correlation",
        "how residential sorting reinforces school inequality",
        "how a moral panic grows through feedback between media and institutions",
        "why institutions continue after their original purpose disappears",
    ),
    "Culture": (
        "how slang marks belonging before entering standard language",
        "why recipes change when ingredients cross a border",
        "how a mourning ritual coordinates private grief and public memory",
        "how clothing rules signal rank without spoken explanation",
        "why revived traditions can feel ancient despite recent origins",
    ),
    "Linguistics": (
        "how the Great Vowel Shift changed pronunciation without changing spelling",
        "why grammatical gender does not necessarily describe biological sex",
        "how children infer grammar from incomplete examples",
        "how tone changes word meaning without changing consonants",
        "why frequently used words erode faster in speech",
    ),
    "Philosophy": (
        "how the Ship of Theseus separates identity from material continuity",
        "why Gettier cases challenge the idea of justified true belief",
        "how the veil of ignorance removes knowledge of personal advantage",
        "why the experience machine tests whether pleasure is enough",
        "how the sorites paradox makes vague boundaries unstable",
    ),
    "Ethics": (
        "why trolley problems separate intention from predicted consequence",
        "how informed consent changes when understanding is incomplete",
        "why algorithmic fairness definitions can conflict mathematically",
        "how moral luck changes judgments about identical decisions",
        "why future generations are difficult to represent in present choices",
    ),
    "Art History": (
        "how linear perspective reorganized space in Renaissance painting",
        "why Impressionists painted colored shadows outdoors",
        "how ukiyo-e composition influenced European modernism",
        "how patronage shaped what appeared in a public fresco",
        "why photography changed the purpose of painted portraiture",
    ),
    "Music Theory": (
        "how a dominant seventh chord creates pressure to resolve",
        "why syncopation makes an expected beat feel displaced",
        "how equal temperament makes every key usable at a small tuning cost",
        "how a pedal tone changes chords while one note remains fixed",
        "why overtones make two instruments sound different on the same note",
    ),
    "Photography": (
        "how aperture changes both exposure and depth of field",
        "why rolling shutters bend a fast-moving subject",
        "how focal length changes perspective only when camera position changes",
        "how a polarizing filter removes selected reflections",
        "why sensor noise becomes visible in dark exposures",
    ),
    "Filmmaking": (
        "how match cuts connect two scenes through shape or motion",
        "why the 180-degree rule preserves screen direction",
        "how rack focus redirects attention without moving the camera",
        "how practical light motivates a scene's hidden fixtures",
        "why frame rate changes the texture of motion",
    ),
    "Product Design": (
        "how progressive disclosure keeps a complex interface usable",
        "why affordances let an object suggest its own operation",
        "how a design system turns repeated choices into reusable tokens",
        "how error prevention differs from a helpful error message",
        "why perceived latency matters even when total time is unchanged",
    ),
}

BASE_TOPICS = tuple(TOPIC_SUBTOPICS)


CONTENT_ANGLES = (
    {
        "id": "mechanism",
        "label": "Inside the mechanism",
        "instruction": "Follow the input through named parts or stages until it becomes an observable output.",
    },
    {
        "id": "failure_mode",
        "label": "Failure mode",
        "instruction": "Establish normal operation, then trace one broken link and its consequences.",
    },
    {
        "id": "experiment",
        "label": "Decisive experiment",
        "instruction": "Explain the setup, the observation, and the conclusion while separating evidence from interpretation.",
    },
    {
        "id": "tradeoff",
        "label": "Hidden tradeoff",
        "instruction": "Show why improving one measurable property makes another property harder to preserve.",
    },
    {
        "id": "case_study",
        "label": "Concrete case",
        "instruction": "Use one named object, event, system, or situation to reveal the broader mechanism.",
    },
    {
        "id": "comparison",
        "label": "Close comparison",
        "instruction": "Compare two easily confused mechanisms and identify the exact step where they diverge.",
    },
)
