apiVersion: v1
kind: Service
metadata:
  name: chat-service
  namespace: smarty
spec:
  type: LoadBalancer
  selector:
    app: chat-service
    version: blue
  ports:
    - port: 80
      targetPort: 8000